repository: X65/x65.github.io
url: https://x65.zone
title: X65 - Modern 8-bit computer for Creativity, Learning, and Retro Gaming
tagline: Modern 8-bit computer
description: |
  X65 is a modern 8-bit microcomputer built around the W65C816 CPU, featuring 16 MB flat RAM, custom CGIA video with 256-color palette, sprites, layers, and scrolling, Yamaha SD-1 FM audio plus DAC sampling, USB and Wi-Fi/Bluetooth, and its native OS/816 for multitasking, shell access, and low-level programming.

author:
  twitter: X65pc
twitter:
  username: X65pc
  card: summary_large_image
social:
  name: X65 Project
  links:
    - https://github.com/X65
    - https://discord.gg/TuTe3kymgy
    - https://x.com/X65pc
    - https://www.youtube.com/@X65pc
    - https://patreon.com/X65pc
logo: /assets/paw_logo_512.png
timezone: Europe/Warsaw

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
