repository: X65/x65.github.io
url: https://x65.zone

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

posthog_api_key: phc_UQn7P52g9r5tEcD6wIIkFnNCL4teOAg8ItastJri7vF
posthog_host: https://eu.i.posthog.com
