repository: X65/x65.github.io
url: https://x65.zone

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

highlighter: rouge
markdown: kramdown

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"
