repository: X65/x65.github.io
url: https://x65.zone
title: X65 - Modern 8-bit microcomputer
tagline: Modern 8-bit microcomputer
description: X65 is an effort to build an 8-bit microcomputer for the modern era. It uses best of breed components and strives to keep 8-bit feeling, while being usable for daily basis computing activities.

social:
  links:
    - https://github.com/X65
    - https://discord.gg/TuTe3kymgy

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

posthog_api_key: phc_UQn7P52g9r5tEcD6wIIkFnNCL4teOAg8ItastJri7vF
posthog_host: https://eu.i.posthog.com
