var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var ma=f.wasmBinary,na,p=!1,oa,r,t,pa,qa,u,v,x,ra,y,sa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://");
function ta(){var a=na.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a);f.HEAP64=ra=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var z=0,A=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Aa&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!(ma||"function"!=typeof WebAssembly.instantiateStreaming||sa(b)||ka(b)||ca))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
var Ea={647688:()=>{f._webapi_input=a=>{B(()=>f._webapi_input_internal(C(a)))};f._webapi_load_file=a=>{B(()=>f._webapi_load_file_internal(C(a)))}},647946:a=>{let b=navigator.getGamepads();return b?(a=b[a])&&a.vibrationActuator?1:0:0},648121:(a,b,c)=>{let d=navigator.getGamepads();if(!d)return 0;a=d[a];if(!a||!a.vibrationActuator)return 0;a.vibrationActuator.playEffect("dual-rumble",{startDelay:0,duration:3E3,weakMagnitude:c/65535,strongMagnitude:b/65535});return 1}};
class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ga=a=>{for(;0<a.length;)a.shift()(f)},Ha=f.noExitRuntime||!0,Ia=[],Ja,D=a=>{var b=Ia[a];b||(a>=Ia.length&&(Ia.length=a+1),Ia[a]=b=Ja.get(a));return b},Ka="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|
g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},La={},Ma=0,Na={},Oa=a=>{a instanceof Fa||"unwind"==a||ha(1,a)},Pa=a=>{oa=a;Ha||0<Ma||(f.onExit?.(a),p=!0);ha(a,new Fa(a))},Qa=a=>{oa=a;Pa(a)},Ra=()=>{if(!(Ha||0<Ma))try{var a=oa;oa=a;Pa(a)}catch(b){Oa(b)}},Sa=a=>{if(!p)try{a(),Ra()}catch(b){Oa(b)}},F=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);
if(55296<=g&&57343>=g){var l=a.charCodeAt(++h);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},Ta=[],bb=(a,b)=>{Ua=a;Va=b;if(Wa)if(Xa||=!0,0==a)H=function(){setTimeout(Ya,Math.max(0,Za+b-performance.now())|0)};else if(1==a)H=function(){$a(Ya)};else if(2==a){if("undefined"==
typeof ab)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);ab=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else ab=setImmediate;H=function(){ab(Ya)}}},kb=(a,b,c,d,e)=>{function h(){return g<cb?(Ra(),!1):!0}Wa=a;db=d;var g=cb;Xa=!1;Ya=function(){if(!p)if(0<
eb.length){var l=eb.shift();l.lf(l.$e);if(fb){var m=fb,q=0==m%1?m-1:Math.floor(m);fb=l.cf?q:(8*m+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=fb??0,q=gb.hf??0,m?m<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));h()&&setTimeout(Ya,0)}else if(h())if(hb=hb+1|0,1==Ua&&1<Va&&0!=hb%Va)H();else{0==Ua&&(Za=performance.now());a:if(!p){for(l of ib)if(!1===l())break a;Sa(a);for(m of jb)m()}h()&&H()}};e||(0<b?bb(0,1E3/b):bb(1,1),H());if(c)throw"unwind";
},Xa=!1,H=null,cb=0,Wa=null,db=0,Ua=0,Va=0,hb=0,eb=[],ib=[],jb=[];function lb(){H=null;cb++}var mb=0;function $a(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===mb)mb=b+1E3/60;else for(;b+2>=mb;)mb+=1E3/60;setTimeout(a,Math.max(mb-b,0))}}var gb={},Za,Ya,ab,fb;function nb(a){var b=I.Md[a];b.target.removeEventListener(b.Hd,b.Ge,b.Jd);I.Md.splice(a,1)}
function ob(){if(navigator.userActivation?navigator.userActivation.isActive:I.pe&&I.Ue.ae){var a=I.Pd;I.Pd=[];for(var b of a)b.ue(...b.Ce)}}function J(a){if(!a.target)return-4;if(a.Kd)a.Ge=function(c){++I.pe;I.Ue=a;ob();a.Ld(c);ob();--I.pe},a.target.addEventListener(a.Hd,a.Ge,a.Jd),I.Md.push(a);else for(var b=0;b<I.Md.length;++b)I.Md[b].target==a.target&&I.Md[b].Hd==a.Hd&&nb(b--);return 0}function pb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={af:0,oe:0,qe:0,ge:0,ze:0,we:0,me:0,ff:0,sf:0,be:0,ne:0,te:0,Af:0,ve:0,pf(a,b,c){r.set(r.subarray(b,b+c),a)},uf(){for(;I.Md.length;)nb(I.Md.length-1);I.Pd=[]},pe:0,Pd:[],ef(a,b,c){function d(h,g){if(h.length!=g.length)return!1;for(var l in h)if(h[l]!=g[l])return!1;return!0}for(var e of I.Pd)if(e.ue==a&&d(e.Ce,c))return;I.Pd.push({ue:a,Ke:b,Ce:c});I.Pd.sort((h,g)=>h.Ke<g.Ke)},wf(a){I.Pd=I.Pd.filter(b=>b.ue!=a)},Md:[],vf:(a,b)=>{for(var c=0;c<I.Md.length;++c)I.Md[c].target!=a||b&&b!=I.Md[c].Hd||
nb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},qb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],L=a=>{a=2<a?a?E(t,a):"":a;return qb[a]||("undefined"!=typeof document?document.querySelector(a):null)},rb=a=>0>qb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},sb=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+8*c+528>>3]="object"==typeof b.buttons[c]?
b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;F(b.id,a+1112,64);F(b.mapping,a+1176,64)},tb=()=>{try{if(navigator.getGamepads)return(I.ce=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},ub=(a,b,c,d,e,h)=>{I.me||(I.me=M(256));a={target:L(a),Hd:h,Kd:d,Ld:(g=event)=>{var l=g.target.id?
g.target.id:"",m=I.me;F(pb(g.target),m+0,128);F(l,m+128,128);D(d)(e,m,b)&&g.preventDefault()},Jd:c};return J(a)},vb=(a,b,c)=>{I.be||(I.be=M(80));b={target:L(2),Hd:"devicemotion",Kd:c,Ld:(d=event)=>{var e=I.be,h=d.acceleration,g=d.accelerationIncludingGravity,l=d.rotationRate;h=h||{};g=g||{};l=l||{};y[e>>3]=h.x;y[e+8>>3]=h.y;y[e+16>>3]=h.z;y[e+24>>3]=g.x;y[e+32>>3]=g.y;y[e+40>>3]=g.z;y[e+48>>3]=l.alpha;y[e+56>>3]=l.beta;y[e+64>>3]=l.gamma;D(c)(17,I.be,a)&&d.preventDefault()},Jd:b};return J(b)},wb=
(a,b,c,d,e)=>{I.ne||(I.ne=M(276));return J({target:a,Hd:e,Kd:d,Ld:(h=event)=>{var g=I.ne,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!l;r[g]=m;r[g+1]=I.fullscreenEnabled();var q=m?l:I.Ye,w=q?.id||"";F(pb(q),g+2,128);F(w,g+130,128);u[g+260>>2]=q?q.clientWidth:0;u[g+264>>2]=q?q.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;m&&(I.Ye=l);D(d)(19,g,b)&&h.preventDefault()},Jd:c})},xb=(a,b,c,d,e)=>{I.oe||
(I.oe=M(1240));b={target:L(2),ae:!0,Hd:e,Kd:c,Ld:(h=event)=>{var g=I.oe;sb(g,h.gamepad);D(c)(d,g,a)&&h.preventDefault()},Jd:b};return J(b)},yb=(a,b,c,d,e,h)=>{I.qe||(I.qe=M(160));a={target:L(a),Hd:h,Kd:d,Ld:g=>{var l=I.qe;y[l>>3]=g.timeStamp;var m=l>>2;u[m+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[m+5]=g.charCode;u[m+6]=g.keyCode;u[m+7]=g.which;F(g.key||"",l+32,32);F(g.code||"",l+64,32);F(g.char||"",l+96,32);F(g.locale||"",l+128,32);D(d)(e,
l,b)&&g.preventDefault()},Jd:c};return J(a)},zb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=rb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Ab=(a,b,c,d,e,h)=>{I.ge||(I.ge=M(64));a=L(a);return J({target:a,ae:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Hd:h,Kd:d,Ld:(g=
event)=>{zb(I.ge,g,a);D(d)(e,I.ge,b)&&g.preventDefault()},Jd:c})},Bb=(a,b,c,d,e)=>{I.te||(I.te=M(257));return J({target:a,Hd:e,Kd:d,Ld:(h=event)=>{var g=I.te,l=document.pointerLockElement||document.Xd||document.Be||document.Ae;r[g]=!!l;var m=l?.id||"";F(pb(l),g+1,128);F(m,g+129,128);D(d)(20,g,b)&&h.preventDefault()},Jd:c})},Cb=(a,b,c,d,e)=>J({target:a,Hd:e,Kd:d,Ld:(h=event)=>{D(d)(38,0,b)&&h.preventDefault()},Jd:c}),Db=(a,b,c,d)=>{I.we||(I.we=M(36));a=L(a);return J({target:a,Hd:"resize",Kd:d,Ld:(e=
event)=>{if(e.target==a){var h=document.body;if(h){var g=I.we;u[g>>2]=0;u[g+4>>2]=h.clientWidth;u[g+8>>2]=h.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;D(d)(10,g,b)&&e.preventDefault()}}},Jd:c})},Eb=(a,b,c,d,e,h)=>{I.ve||(I.ve=M(1552));a=L(a);return J({target:a,ae:"touchstart"==h||"touchend"==h,Hd:h,Kd:d,Ld:g=>{var l={},m=g.touches;for(var q of m)q.He=q.Je=0,l[q.identifier]=q;for(var w of g.changedTouches)w.He=
1,l[w.identifier]=w;for(var K of g.targetTouches)l[K.identifier].Je=1;m=I.ve;y[m>>3]=g.timeStamp;r[m+12]=g.ctrlKey;r[m+13]=g.shiftKey;r[m+14]=g.altKey;r[m+15]=g.metaKey;q=m+16;w=rb(a);K=0;for(let G of Object.values(l))if(l=q>>2,u[l]=G.identifier,u[l+1]=G.screenX,u[l+2]=G.screenY,u[l+3]=G.clientX,u[l+4]=G.clientY,u[l+5]=G.pageX,u[l+6]=G.pageY,r[q+28]=G.He,r[q+29]=G.Je,u[l+8]=G.clientX-(w.left|0),u[l+9]=G.clientY-(w.top|0),q+=48,31<++K)break;u[m+8>>2]=K;D(d)(e,m,b)&&g.preventDefault()},Jd:c})},N,Fb=
a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,g)=>b.drawElementsInstancedANGLE(c,d,e,h,g))},Gb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
Hb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Ib=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Jb=1,O=[],P=[],Kb=[],Lb=[],Q=[],R=[],Mb=[],Nb=[],S=[],Ob=[1,1,2,2,4,4,4,2,3,4,8],Pb={},Qb=4,Rb=0,Sb=a=>{for(var b=Jb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=N[c](),g=h&&Sb(d);h?(h.name=g,d[g]=h):T||=1282;u[b+4*e>>2]=g}},Tb=a=>{a=32-Math.clz32(0===a?0:a-1);var b=V.Vd[a];if(b)return b;b=N.getParameter(34965);V.Vd[a]=N.createBuffer();N.bindBuffer(34963,V.Vd[a]);N.bufferData(34963,1<<a,35048);N.bindBuffer(34963,
b);return V.Vd[a]},Vb=a=>{Ub=!1;for(var b=0;b<V.re;++b){var c=V.Rd[b];if(c.Sd&&c.enabled){Ub=!0;var d=c.ie;d=0<d?a*d:c.size*Ob[c.type-5120]*a;var e=32-Math.clz32(0===d?0:d-1);var h=V.Wd[e],g=V.Qd[e];V.Qd[e]=V.Qd[e]+1&63;var l=h[g];l?e=l:(l=N.getParameter(34964),h[g]=N.createBuffer(),N.bindBuffer(34962,h[g]),N.bufferData(34962,1<<e,35048),N.bindBuffer(34962,l),e=h[g]);N.bindBuffer(34962,e);N.bufferSubData(34962,0,t.subarray(c.he,c.he+d));c.ye.call(N,b,c.size,c.type,c.se,c.ie,0)}}},Xb=(a,b)=>{a.Xd||
(a.Xd=a.getContext,a.getContext=function(d,e){e=a.Xd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Ie?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Wb(c,b):0},Wb=(a,b)=>{var c=Sb(Nb),d={handle:c,attributes:b,version:b.Ie,ke:a};a.canvas&&(a.canvas.Ze=d);Nb[c]=d;("undefined"==typeof b.Fe||b.Fe)&&Yb(d);d.re=d.ke.getParameter(34921);d.Rd=[];for(a=0;a<d.re;a++)d.Rd[a]={enabled:!1,Sd:!1,size:0,type:0,se:0,ie:0,he:0,ye:null};d.Qd=[];d.je=[];d.Qd.length=d.je.length=
22;d.Wd=[];d.Zd=[];d.Wd.length=d.Zd.length=22;d.Vd=[];d.Vd.length=22;for(a=0;21>=a;++a){d.Vd[a]=null;d.Qd[a]=d.je[a]=0;d.Wd[a]=[];d.Zd[a]=[];b=d.Wd[a];var e=d.Zd[a];b.length=e.length=64;for(var h=0;64>h;++h)b[h]=e[h]=null}return c},Yb=a=>{a||=V;if(!a.Xe){a.Xe=!0;var b=a.ke;b.rf=b.getExtension("WEBGL_multi_draw");b.kf=b.getExtension("EXT_polygon_offset_clamp");b.jf=b.getExtension("EXT_clip_control");b.Bf=b.getExtension("WEBGL_polygon_mode");Fb(b);Gb(b);Hb(b);b.gf=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.nf=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ee=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ee)b.Ee=b.getExtension("EXT_disjoint_timer_query");Ib(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Ub,Zb=(a,b,c,d,e,h)=>{a={target:L(a),Hd:h,Kd:d,Ld:(g=event)=>{D(d)(e,0,b)&&g.preventDefault()},Jd:c};J(a)},$b=(a,b,c,d)=>{I.ze||(I.ze=M(96));return J({target:a,ae:!0,Hd:"wheel",Kd:d,Ld:(e=event)=>
{var h=I.ze;zb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>3]=e.deltaZ;u[h+88>>2]=e.deltaMode;D(d)(9,h,b)&&e.preventDefault()},Jd:c})},ac=["default","low-power","high-performance"],bc={},dc=()=>{if(!cc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in bc)void 0===bc[b]?delete a[b]:a[b]=bc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
cc=c}return cc},cc,ec=[null,[],[]],fc=[],gc=()=>{var a=Ib(N);return a=a.concat(a.map(b=>"GL_"+b))},hc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=gc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;
case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},ic=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},jc=a=>{var b=ic(a)+1,c=M(b);c&&F(a,c,b);return c},kc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),lc=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?v:qa},W=a=>{var b=N.Ve;if(b){var c=b.$d[a];"number"==typeof c&&(b.$d[a]=c=N.getUniformLocation(b,b.Se[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],mc=[],C=a=>{var b=ic(a)+1,c=nc(b);F(a,c,b);return c},B=a=>{var b=oc();a();pc(b)};f.requestAnimationFrame=$a;f.pauseMainLoop=lb;f.resumeMainLoop=function(){cb++;var a=Ua,b=Va,c=Wa;Wa=null;kb(c,0,!1,db,!0);bb(a,b);H()};f.preMainLoop&&ib.push(f.preMainLoop);f.postMainLoop&&jb.push(f.postMainLoop);
var qc=()=>{if(V){var a=V.Wd;V.Wd=V.Zd;V.Zd=a;a=V.Qd;V.Qd=V.je;V.je=a;for(a=0;21>=a;++a)V.Qd[a]=0}};"undefined"!=typeof gb&&ib.push(qc);for(var Y=0;32>Y;++Y)fc.push(Array(Y));var rc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=rc.subarray(0,Y);var sc=new Int32Array(288);for(Y=0;288>=Y;++Y)mc[Y]=sc.subarray(0,Y);
var Jc={Ob:function(a){a=navigator.getGamepads()[a];if(0<a.id.indexOf("Product: ")){let b=a.id.indexOf("Product: ")+9;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[1],16))?parseInt(a[1],16):0},Pb:function(a){a=navigator.getGamepads()[a];if(0<a.id.indexOf("Vendor: ")){let b=a.id.indexOf("Vendor: ")+8;return parseInt(a.id.substr(b,4),16)}a=a.id.split("-");return 1<a.length&&!isNaN(parseInt(a[0],16))?parseInt(a[0],16):0},Nb:function(a){return 0<=navigator.getGamepads()[a].id.toLowerCase().indexOf("xinput")},
pb:(a,b)=>D(a)(b),ja:function(){return 0},Fb:a=>{La.mf(a);return 0},Ab:()=>{},Db:function(){return 0},yb:()=>{},xb:()=>{},Eb:function(){},zb:()=>{},Hb:()=>za(""),rb:()=>{Ha=!1;Ma=0},sb:(a,b)=>{Na[a]&&(clearTimeout(Na[a].id),delete Na[a]);if(!b)return 0;var c=setTimeout(()=>{delete Na[a];Sa(()=>tc(a,performance.now()))},b);Na[a]={id:c,zf:b};return 0},tb:(a,b,c,d)=>{var e=(new Date).getFullYear(),h=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(h,e);
u[b>>2]=Number(h!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(h);b=b(e);e<h?(F(a,c,17),F(b,d,17)):(F(a,d,17),F(b,c,17))},Gb:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Z:function(a){if(void 0===window.localStorage)return 0;a=a?E(t,a):"";return(a=window.localStorage.getItem(a))?jc(a):0},ob:function(a,b){void 0!==window.localStorage&&
(a=a?E(t,a):"",b=b?E(t,b):"",window.localStorage.setItem(a,b))},C:(a,b,c)=>{Ta.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Ta.push(112==d?v[c>>2]:106==d?ra[c>>3]:105==d?u[c>>2]:y[c>>3]);c+=e?8:4}return Ea[a](...Ta)},fc:()=>{lb();Wa=null},la:()=>Date.now(),wa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Ha:(a,b,c)=>{a=L(a);if(!a)return-4;a=rb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},oa:(a,b)=>{if(0>a||a>=I.ce.length)return-5;if(!I.ce[a])return-7;sb(b,I.ce[a]);
return 0},vb:()=>2147483648,j:()=>performance.now(),Qb:()=>I.ce.length,Mb:()=>0,gc:()=>performance.now(),jb:(a,b)=>{function c(d){D(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ub:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ta();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},pa:tb,
V:(a,b,c,d)=>ub(a,b,c,d,12,"blur"),va:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},Kb:(a,b,c)=>vb(a,b,c),W:(a,b,c,d)=>ub(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!I.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;wb(a,b,c,d,"webkitfullscreenchange");return wb(a,b,c,d,"fullscreenchange")},u:(a,b,c)=>tb()?-1:xb(a,b,c,26,"gamepadconnected"),t:(a,b,c)=>tb()?-1:xb(a,b,c,27,"gamepaddisconnected"),ea:(a,b,c,d)=>yb(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>yb(a,b,c,d,1,"keypress"),da:(a,b,c,d)=>
yb(a,b,c,d,3,"keyup"),kb:(a,b,c)=>{a=D(a);kb(a,b,c)},na:(a,b,c,d)=>Ab(a,b,c,d,5,"mousedown"),ha:(a,b,c,d)=>Ab(a,b,c,d,33,"mouseenter"),ga:(a,b,c,d)=>Ab(a,b,c,d,34,"mouseleave"),ia:(a,b,c,d)=>Ab(a,b,c,d,8,"mousemove"),ka:(a,b,c,d)=>Ab(a,b,c,d,6,"mouseup"),Y:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Xd||document.body.Be||document.body.Ae))return-1;a=L(a);if(!a)return-4;Bb(a,b,c,d,"mozpointerlockchange");Bb(a,b,c,d,"webkitpointerlockchange");Bb(a,b,c,
d,"mspointerlockchange");return Bb(a,b,c,d,"pointerlockchange")},X:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Xd||document.body.Be||document.body.Ae))return-1;a=L(a);if(!a)return-4;Cb(a,b,c,d,"mozpointerlockerror");Cb(a,b,c,d,"webkitpointerlockerror");Cb(a,b,c,d,"mspointerlockerror");return Cb(a,b,c,d,"pointerlockerror")},ya:(a,b,c,d)=>Db(a,b,c,d),_:(a,b,c,d)=>Eb(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>Eb(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>Eb(a,b,c,d,24,"touchmove"),
ba:(a,b,c,d)=>Eb(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{Zb(a,b,c,d,31,"webglcontextlost");return 0},S:(a,b,c,d)=>{Zb(a,b,c,d,32,"webglcontextrestored");return 0},fa:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?$b(a,b,c,d):-1:-4,Lb:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},hc:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+
5],powerPreference:ac[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Ie:u[c+4],qf:u[c+5],Fe:r[b+24],We:r[b+25],tf:u[c+7],xf:r[b+32]};a=L(a);return!a||b.We?0:Xb(a,b)},$b:a=>{V=Nb[a];f.ctx=N=V?.ke;return!a||N?0:-5},Ib:(a,b)=>{var c=0;dc().forEach((d,e)=>{var h=b+c;e=v[a+4*e>>2]=h;for(h=0;h<d.length;++h)r[e++]=d.charCodeAt(h);r[e]=0;c+=d.length+1});return 0},Jb:(a,b)=>{var c=dc();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ma:()=>52,Cb:()=>52,wb:function(){return 70},Bb:(a,
b,c,d)=>{for(var e=0,h=0;h<c;h++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var q=t[g+m],w=ec[a];0===q||10===q?((1===a?la:n)(E(w)),w.length=0):w.push(q)}e+=l}v[d>>2]=e;return 0},Ic:function(a,b,c){const d=a?E(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+h)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var h=e.result;let g;try{g=
h.transaction(["store"],"readwrite")}catch(q){console.log("fs_js_load_snapshot: db.transaction failed with",q);return}h=g.objectStore("store");const l=d+"_"+b,m=h.get(l);m.onsuccess=()=>{if(void 0!==m.result){const q=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",q,"bytes");const w=uc(q);t.set(m.result,w);vc(c,w,q)}else vc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};
e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},Jc:function(a,b,c,d){const e=a?E(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let h;try{h=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}h.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");h.result.createObjectStore("store")};h.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const g=h.result.transaction(["store"],
"readwrite");var l=g.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};h.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},p:a=>N.activeTexture(a),z:(a,b)=>{N.attachShader(P[a],R[b])},a:(a,b)=>{34962==a?N.Td=b:34963==a&&(N.Yd=b);35051==a?N.De=
b:35052==a&&(N.Ud=b);N.bindBuffer(a,O[b])},D:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Hc:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},h:(a,b)=>{N.bindFramebuffer(a,Kb[b])},Ma:(a,b)=>{N.bindRenderbuffer(a,Lb[b])},o:(a,b)=>{N.bindSampler(a,S[b])},c:(a,b)=>{N.bindTexture(a,Q[b])},Q:a=>{N.bindVertexArray(Mb[a]);a=N.getParameter(34965);N.Yd=a?a.name|0:0},Ba:(a,b,c,d)=>N.blendColor(a,b,c,d),Ca:(a,b)=>N.blendEquationSeparate(a,b),Da:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),oc:(a,b,c,d,e,h,g,l,m,q)=>N.blitFramebuffer(a,
b,c,d,e,h,g,l,m,q),Ya:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},M:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},Rb:a=>N.checkFramebufferStatus(a),Ja:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),G:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},Ia:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},k:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Tb:a=>{N.compileShader(R[a])},Zb:(a,b,c,d,e,h,g,l,m)=>{2<=V.version?
N.Ud||!l?N.compressedTexSubImage2D(a,b,c,d,e,h,g,l,m):N.compressedTexSubImage2D(a,b,c,d,e,h,g,t,m,l):N.compressedTexSubImage2D(a,b,c,d,e,h,g,t.subarray(m,m+l))},Xb:(a,b,c,d,e,h,g,l,m,q,w)=>{N.Ud?N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,m,q,w):N.compressedTexSubImage3D(a,b,c,d,e,h,g,l,m,t,w,q)},Sa:()=>{var a=Sb(P),b=N.createProgram();b.name=a;b.fe=b.de=b.ee=0;b.xe=1;P[a]=b;return a},Vb:a=>{var b=Sb(R);R[b]=N.createShader(a);return b},Aa:a=>N.cullFace(a),_b:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*
c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Td&&(N.Td=0),d==N.Yd&&(N.Yd=0),d==N.De&&(N.De=0),d==N.Ud&&(N.Ud=0))}},A:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Kb[d];e&&(N.deleteFramebuffer(e),e.name=0,Kb[d]=null)}},m:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},N:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Lb[d];e&&(N.deleteRenderbuffer(e),e.name=0,Lb[d]=null)}},O:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=
0,S[d]=null)}},l:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},_a:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];N.deleteVertexArray(Mb[d]);Mb[d]=null}},v:a=>N.depthFunc(a),w:a=>{N.depthMask(!!a)},d:a=>N.disable(a),xa:a=>{V.Rd[a].enabled=!1;N.disableVertexAttribArray(a)},qc:(a,b,c)=>{Vb(b+c);N.drawArrays(a,b,c);Ub&&N.bindBuffer(34962,O[N.Td])},rc:(a,b,c,d)=>{N.drawArraysInstanced(a,
b,c,d)},H:(a,b)=>{for(var c=fc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];N.drawBuffers(c)},sc:(a,b,c,d)=>{var e=0;if(!N.Yd){var h=1*Ob[c-5120]*b;var g=Tb(h);N.bindBuffer(34963,g);N.bufferSubData(34963,0,t.subarray(d,d+h));if(0<b)for(g=0;g<V.re;++g)if(h=V.Rd[g],h.Sd&&h.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:T||=1282;return}e=(new e(t.buffer,d,b)).reduce((l,m)=>Math.max(l,m))+1;break}d=0}Vb(e);N.drawElements(a,b,c,d);Ub&&N.bindBuffer(34962,
O[N.Td]);N.Yd||N.bindBuffer(34963,null)},tc:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},g:a=>N.enable(a),Dc:a=>{V.Rd[a].enabled=!0;N.enableVertexAttribArray(a)},s:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,Lb[d])},f:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},y:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},za:a=>N.frontFace(a),Za:(a,b)=>{U(a,b,"createBuffer",O)},P:(a,b)=>{U(a,b,"createFramebuffer",Kb)},Na:(a,b)=>{U(a,b,"createRenderbuffer",Lb)},Ta:(a,b)=>{U(a,b,"createSampler",
S)},Xa:(a,b)=>{U(a,b,"createTexture",Q)},bb:(a,b)=>{U(a,b,"createVertexArray",Mb)},Oa:(a,b)=>N.getAttribLocation(P[a],b?E(t,b):""),b:(a,b)=>hc(a,b),Ra:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(u[c>>2]=b)},J:(a,b,c)=>{if(c)if(a>=Jb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.fe){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.fe=Math.max(a.fe,N.getActiveUniform(a,
b).name.length+1)}u[c>>2]=a.fe}else if(35722==b){if(!a.de)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.de=Math.max(a.de,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.de}else if(35381==b){if(!a.ee)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.ee=Math.max(a.ee,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.ee}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Sb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(u[c>>2]=b)},ra:(a,b,
c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(R[a],b):T||=1281},cb:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Pb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=gc().map(jc),c=Pb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},I:(a,b)=>{b=b?E(t,b):"";if(a=P[a]){var c=a,d=c.$d,e=c.Te,h;if(!d){c.$d=d={};
c.Se={};var g=N.getProgramParameter(c,35718);for(h=0;h<g;++h){var l=N.getActiveUniform(c,h);var m=l.name;l=l.size;var q=kc(m);q=0<q?m.slice(0,q):m;var w=c.xe;c.xe+=l;e[q]=[l,w];for(m=0;m<l;++m)d[w]=m,c.Se[w++]=q}}c=a.$d;d=0;e=b;h=kc(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.Te[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},nc:(a,b,c)=>{for(var d=fc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];N.invalidateFramebuffer(a,d)},K:a=>{a=P[a];N.linkProgram(a);
a.$d=0;a.Te={}},ab:(a,b)=>{3317==a?Qb=b:3314==a&&(Rb=b);N.pixelStorei(a,b)},Ga:(a,b)=>N.polygonOffset(a,b),pc:a=>N.readBuffer(a),La:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),L:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},e:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},x:(a,b,c,d)=>N.scissor(a,b,c,d),Ub:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var g=(g=v[c+4*h>>2])?E(t,g,d?v[d+4*h>>2]:void 0):"";e+=g}N.shaderSource(R[a],e)},bc:(a,b,c)=>N.stencilFunc(a,b,c),Fa:(a,b,c,d)=>N.stencilFuncSeparate(a,
b,c,d),q:a=>N.stencilMask(a),ac:(a,b,c)=>N.stencilOp(a,b,c),Ea:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Wa:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ua:(a,b,c,d,e,h)=>N.texStorage3D(a,b,c,d,e,h),Yb:(a,b,c,d,e,h,g,l,m)=>{if(2<=V.version){if(N.Ud){N.texSubImage2D(a,b,c,d,e,h,g,l,m);return}if(m){var q=lc(l);N.texSubImage2D(a,b,c,d,e,h,g,l,q,m>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(m){q=lc(l);var w=h*((Rb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+
Qb-1&-Qb);m=q.subarray(m>>>31-Math.clz32(q.BYTES_PER_ELEMENT),m+w>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else m=null;N.texSubImage2D(a,b,c,d,e,h,g,l,m)},Wb:(a,b,c,d,e,h,g,l,m,q,w)=>{if(N.Ud)N.texSubImage3D(a,b,c,d,e,h,g,l,m,q,w);else if(w){var K=lc(q);N.texSubImage3D(a,b,c,d,e,h,g,l,m,q,K,w>>>31-Math.clz32(K.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,h,g,l,m,q,null)},Cc:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=
x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Pa:(a,b)=>{N.uniform1i(W(a),b)},yc:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=mc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Bc:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},xc:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),
u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=mc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Ac:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},wc:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=mc[b],e=0;e<b;e+=3)d[e]=
u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},zc:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},vc:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=mc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+
(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},uc:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=h[l];e[g+1]=h[l+1];e[g+2]=h[l+2];e[g+3]=h[l+3];e[g+4]=h[l+4];e[g+5]=h[l+5];e[g+6]=h[l+6];e[g+7]=h[l+7];e[g+8]=h[l+8];e[g+9]=h[l+9];e[g+10]=h[l+10];e[g+11]=h[l+11];e[g+12]=h[l+12];e[g+13]=h[l+13];e[g+14]=h[l+14];e[g+15]=h[l+15]}}else e=
x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},n:a=>{a=P[a];N.useProgram(a);N.Ve=a},Ec:(a,b)=>{N.vertexAttribDivisor(a,b)},Fc:(a,b,c,d,e)=>{var h=V.Rd[a];N.Td?(h.Sd=!1,N.vertexAttribIPointer(a,b,c,d,e)):(h.size=b,h.type=c,h.se=!1,h.ie=d,h.he=e,h.Sd=!0,h.ye=function(g,l,m,q,w,K){this.vertexAttribIPointer(g,l,m,w,K)})},Gc:(a,b,c,d,e,h)=>{var g=V.Rd[a];N.Td?(g.Sd=!1,N.vertexAttribPointer(a,b,c,!!d,e,h)):(g.size=b,g.type=c,g.se=d,g.ie=e,g.he=h,g.Sd=!0,g.ye=function(l,m,q,w,K,G){this.vertexAttribPointer(l,
m,q,w,K,G)})},r:(a,b,c,d)=>N.viewport(a,b,c,d),qb:Pa,nb:function(){f.Le=a=>{0!=wc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Le)},mb:function(){f.Re=a=>{const b=a.clipboardData.getData("text");B(()=>{const c=C(b);xc(c)})};window.addEventListener("paste",f.Re)},lb:function(){f.yf=[];f.Me=b=>{b.stopPropagation();b.preventDefault()};f.Ne=b=>{b.stopPropagation();b.preventDefault()};f.Oe=b=>{b.stopPropagation();b.preventDefault()};f.Pe=b=>{b.stopPropagation();b.preventDefault();
const c=b.dataTransfer.files;f.Qe=c;yc(c.length);for(let e=0;e<c.length;e++)B(()=>{const h=C(c[e].name);zc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ac(b.clientX,b.clientY,d)};const a=f.Nd;a.addEventListener("dragenter",f.Me,!1);a.addEventListener("dragleave",f.Ne,!1);a.addEventListener("dragover",f.Oe,!1);a.addEventListener("drop",f.Pe,!1)},gb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ib:function(a){f.le&&
(URL.revokeObjectURL(f.le[a].bf),f.le[a]=null)},eb:function(a){const b=f.Qe;return 0>a||a>=b.length?0:b[a].size},db:function(a,b,c,d,e){const h=new FileReader;h.onload=g=>{g=g.target.result;g.byteLength>d?Bc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),Bc(a,1,0,b,g.byteLength,c,d,e))};h.onerror=()=>{Bc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Qe[a])},Ka:function(a,b){0!==b&&(document.title=b?E(t,b):"");a=a?E(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?qb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
f.Nd=L(a);f.Nd||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.Nd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},ec:function(){window.removeEventListener("beforeunload",f.Le)},dc:function(){window.removeEventListener("paste",f.Re)},cc:function(){const a=f.Nd;a.removeEventListener("dragenter",f.Me);a.removeEventListener("dragleave",f.Ne);a.removeEventListener("dragover",f.Oe);a.removeEventListener("drop",f.Pe)},E:function(){f.Nd&&
f.Nd.requestPointerLock&&f.Nd.requestPointerLock()},R:function(a,b,c){if(f.Nd){if(0===b)a="none";else if(0!=c)a=f.le[a].df;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.Nd.style.cursor=a}},fb:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},hb:function(a){a=a?E(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";
b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ic:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];B(()=>{const e=C(c),h=C(d);Cc(e,h)})}},kc:function(){return f.Od?f.Od.bufferSize:0},mc:function(a,b,c){f.Id=null;f.Od=null;"undefined"!==typeof AudioContext?f.Id=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(f.Id=null,console.log("sokol_audio.h: no WebAudio support"));return f.Id?(console.log("sokol_audio.h: sample rate ",f.Id.sampleRate),f.Od=f.Id.createScriptProcessor(c,0,b),f.Od.onaudioprocess=d=>{const e=d.outputBuffer.length,h=Dc(e);if(h){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<e;q++)m[q]=x[(h>>2)+(g*q+l)]}}},f.Od.connect(f.Id.destination),a=()=>{f.Id&&"suspended"===f.Id.state&&f.Id.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},lc:function(){return f.Id?f.Id.sampleRate:0},ua:function(){const a=f.Id;null!==a&&(f.Od&&f.Od.disconnect(),a.close(),f.Id=null,f.Od=null)},jc:function(){if(f.Id)return"suspended"===f.Id.state?1:0},F:function(a,b,c,d,e,h){const g=b?E(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(g,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>
{m=new Uint8Array(m);m.length<=h?(t.set(m,e),Ec(a,d,m.length)):Fc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,m);Gc(a)}):Hc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${g} failed with: `,l);Gc(a)})},ta:function(a,b){const c=b?E(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),Gc(a)):Ic(a,Number(d))):Hc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,
d);Gc(a)})},qa:function(){return navigator.userAgent.includes("Macintosh")?1:0},sa:function(a,b){b=b?E(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},$a:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Va:function(){console.log("webapi_js_event_reboot()");f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},
Qa:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},B:function(a,b){console.log("webapi_js_event_stopped()");f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Kc;ta();Ja=Z.Pc;va.unshift(Z.Lc);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:Jc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=sa("emu.wasm")?"emu.wasm":f.locateFile?f.locateFile("emu.wasm",k):k+"emu.wasm";return a((await Da(b)).instance)})();
var uc=f._fs_emsc_alloc=a=>(uc=f._fs_emsc_alloc=Z.Mc)(a),M=a=>(M=Z.Nc)(a),vc=f._fs_emsc_load_snapshot_callback=(a,b,c)=>(vc=f._fs_emsc_load_snapshot_callback=Z.Oc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.Qc)();f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.Rc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.Sc)(a);f._webapi_free=a=>(f._webapi_free=Z.Tc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.Uc)();f._webapi_reset=()=>(f._webapi_reset=Z.Vc)();
f._webapi_ready=()=>(f._webapi_ready=Z.Wc)();f._webapi_load=(a,b)=>(f._webapi_load=Z.Xc)(a,b);f._webapi_load_file_internal=a=>(f._webapi_load_file_internal=Z.Yc)(a);f._webapi_unload_file=()=>(f._webapi_unload_file=Z.Zc)();f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z._c)(a);f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.$c)(a);f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.ad)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.bd)(a);
f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.cd)();f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.dd)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.ed)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.fd)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.gd)();f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.hd)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.id)(a,b);
f._webapi_input_internal=a=>(f._webapi_input_internal=Z.jd)(a);
var xc=f.__sapp_emsc_onpaste=a=>(xc=f.__sapp_emsc_onpaste=Z.kd)(a),wc=f.__sapp_html5_get_ask_leave_site=()=>(wc=f.__sapp_html5_get_ask_leave_site=Z.ld)(),yc=f.__sapp_emsc_begin_drop=a=>(yc=f.__sapp_emsc_begin_drop=Z.md)(a),zc=f.__sapp_emsc_drop=(a,b)=>(zc=f.__sapp_emsc_drop=Z.nd)(a,b),Ac=f.__sapp_emsc_end_drop=(a,b,c)=>(Ac=f.__sapp_emsc_end_drop=Z.od)(a,b,c),Bc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,g,l)=>(Bc=f.__sapp_emsc_invoke_fetch_cb=Z.pd)(a,b,c,d,e,h,g,l);
f.__sapp_emsc_set_fullscreen_flag=a=>(f.__sapp_emsc_set_fullscreen_flag=Z.qd)(a);
var Kc=f._main=(a,b)=>(Kc=f._main=Z.rd)(a,b),Dc=f.__saudio_emsc_pull=a=>(Dc=f.__saudio_emsc_pull=Z.sd)(a),Cc=f.__sargs_add_kvp=(a,b)=>(Cc=f.__sargs_add_kvp=Z.td)(a,b),Ic=f.__sfetch_emsc_head_response=(a,b)=>(Ic=f.__sfetch_emsc_head_response=Z.ud)(a,b),Ec=f.__sfetch_emsc_get_response=(a,b,c)=>(Ec=f.__sfetch_emsc_get_response=Z.vd)(a,b,c),Hc=f.__sfetch_emsc_failed_http_status=(a,b)=>(Hc=f.__sfetch_emsc_failed_http_status=Z.wd)(a,b),Fc=f.__sfetch_emsc_failed_buffer_too_small=a=>(Fc=f.__sfetch_emsc_failed_buffer_too_small=
Z.xd)(a),Gc=f.__sfetch_emsc_failed_other=a=>(Gc=f.__sfetch_emsc_failed_other=Z.yd)(a);f._SDL_free=a=>(f._SDL_free=Z.zd)(a);f._SDL_malloc=a=>(f._SDL_malloc=Z.Ad)(a);f._SDL_calloc=(a,b)=>(f._SDL_calloc=Z.Bd)(a,b);f._SDL_realloc=(a,b)=>(f._SDL_realloc=Z.Cd)(a,b);var tc=(a,b)=>(tc=Z.Dd)(a,b),pc=a=>(pc=Z.Ed)(a),nc=a=>(nc=Z.Fd)(a),oc=()=>(oc=Z.Gd)();
function Lc(a=[]){var b=Kc;a.unshift(fa);var c=a.length,d=nc(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=C(g);e+=4});v[e>>2]=0;try{var h=b(c,d);Qa(h)}catch(g){Oa(g)}}
function Mc(a=ea){function b(){f.calledRun=!0;if(!p){Ga(va);Ga(wa);f.onRuntimeInitialized?.();f.noInitialRun||Lc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ga(xa)}}if(0<z)A=Mc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ga(ua);0<z?A=Mc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Mc();
