var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},h="",ia,ja;
if(ca){var fs=require("fs");require("path");h=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?h=self.location.href:"undefined"!=typeof document&&document.currentScript&&(h=document.currentScript.src),h=h.startsWith("blob:")?
"":h.slice(0,h.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var ma=f.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,x,ra,y,sa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://");
function ta(){var a=na.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a);f.HEAP64=ra=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var z=0,A=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Aa&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!(ma||"function"!=typeof WebAssembly.instantiateStreaming||sa(b)||ka(b)||ca))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
var Ea={398668:()=>{f._webapi_input=a=>{B(()=>f._webapi_input_internal(C(a)))};f._webapi_load_file=a=>{B(()=>f._webapi_load_file_internal(C(a)))}}};class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ga=a=>{for(;0<a.length;)a.shift()(f)},Ha=f.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,E=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|g:(e&7)<<18|k<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ja=0,Ka={},La=a=>{a instanceof Fa||"unwind"==a||ha(1,a)},Ma=a=>{oa=a;Ha||0<Ja||(f.onExit?.(a),q=!0);ha(a,new Fa(a))},Na=a=>{oa=a;Ma(a)},Oa=()=>{if(!(Ha||0<Ja))try{var a=oa;oa=a;Ma(a)}catch(b){La(b)}},Pa=a=>{if(!q)try{a(),Oa()}catch(b){La(b)}},Qa=[],Za=(a,b)=>{Ra=a;Sa=b;if(Ta)if(Ua||=!0,0==a)F=function(){setTimeout(Va,Math.max(0,Wa+b-performance.now())|0)};else if(1==a)F=function(){Xa(Va)};else if(2==a){if("undefined"==typeof Ya)if("undefined"==
typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ya=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ya=setImmediate;F=function(){Ya(Va)}}},hb=(a,b,c,d,e)=>{function k(){return g<$a?(Oa(),!1):!0}Ta=a;ab=d;var g=$a;Ua=!1;Va=function(){if(!q)if(0<bb.length){var l=bb.shift();
l.Ie(l.ze);if(cb){var m=cb,p=0==m%1?m-1:Math.floor(m);cb=l.Be?p:(8*m+(p+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=cb??0,p=db.Ge??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(Va,0)}else if(k())if(eb=eb+1|0,1==Ra&&1<Sa&&0!=eb%Sa)F();else{0==Ra&&(Wa=performance.now());a:if(!q){for(l of fb)if(!1===l())break a;Pa(a);for(m of gb)m()}k()&&F()}};e||(0<b?Za(0,1E3/b):Za(1,1),F());if(c)throw"unwind";},Ua=!1,F=null,$a=0,
Ta=null,ab=0,Ra=0,Sa=0,eb=0,bb=[],fb=[],gb=[];function ib(){F=null;$a++}var jb=0;function Xa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jb)jb=b+1E3/60;else for(;b+2>=jb;)jb+=1E3/60;setTimeout(a,Math.max(jb-b,0))}}var db={},Wa,Va,Ya,cb;function kb(a){var b=G.kd[a];b.target.removeEventListener(b.jd,b.Zd,b.ld);G.kd.splice(a,1)}
function lb(){if(navigator.userActivation?navigator.userActivation.isActive:G.Kd&&G.qe.Id){var a=G.rd;G.rd=[];for(var b of a)b.Qd(...b.Vd)}}function H(a){if(!a.target)return-4;if(a.md)a.Zd=function(c){++G.Kd;G.qe=a;lb();a.nd(c);lb();--G.Kd},a.target.addEventListener(a.jd,a.Zd,a.ld),G.kd.push(a);else for(var b=0;b<G.kd.length;++b)G.kd[b].target==a.target&&G.kd[b].jd==a.jd&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var G={Ae:0,Je:0,Ld:0,Gd:0,Ud:0,Sd:0,Jd:0,Ee:0,Ne:0,De:0,He:0,Nd:0,Ve:0,Rd:0,Le(a,b,c){r.set(r.subarray(b,b+c),a)},Pe(){for(;G.kd.length;)kb(G.kd.length-1);G.rd=[]},Kd:0,rd:[],Ce(a,b,c){function d(k,g){if(k.length!=g.length)return!1;for(var l in k)if(k[l]!=g[l])return!1;return!0}for(var e of G.rd)if(e.Qd==a&&d(e.Vd,c))return;G.rd.push({Qd:a,fe:b,Vd:c});G.rd.sort((k,g)=>k.fe<g.fe)},Re(a){G.rd=G.rd.filter(b=>b.Qd!=a)},kd:[],Qe:(a,b)=>{for(var c=0;c<G.kd.length;++c)G.kd[c].target!=a||b&&b!=G.kd[c].jd||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],I=a=>{a=2<a?a?E(t,a):"":a;return nb[a]||("undefined"!=typeof document?document.querySelector(a):null)},ob=a=>0>nb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},pb=[],qb,J=a=>{var b=pb[a];b||(a>=pb.length&&(pb.length=a+1),pb[a]=b=qb.get(a));return b},K=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=
0;k<a.length;++k){var g=a.charCodeAt(k);if(55296<=g&&57343>=g){var l=a.charCodeAt(++k);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},rb=(a,b,c,d,e,k)=>{G.Jd||(G.Jd=L(256));a={target:I(a),jd:k,md:d,nd:(g=event)=>{var l=g.target.id?g.target.id:"",m=G.Jd;K(mb(g.target),m+0,
128);K(l,m+128,128);J(d)(e,m,b)&&g.preventDefault()},ld:c};return H(a)},sb=(a,b,c,d,e,k)=>{G.Ld||(G.Ld=L(160));a={target:I(a),jd:k,md:d,nd:g=>{var l=G.Ld;y[l>>3]=g.timeStamp;var m=l>>2;u[m+2]=g.location;r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;u[m+5]=g.charCode;u[m+6]=g.keyCode;u[m+7]=g.which;K(g.key||"",l+32,32);K(g.code||"",l+64,32);K(g.char||"",l+96,32);K(g.locale||"",l+128,32);J(d)(e,l,b)&&g.preventDefault()},ld:c};return H(a)},tb=(a,b,c)=>{y[a>>
3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ob(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ub=(a,b,c,d,e,k)=>{G.Gd||(G.Gd=L(64));a=I(a);return H({target:a,Id:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,jd:k,md:d,nd:(g=event)=>{tb(G.Gd,g,a);J(d)(e,G.Gd,b)&&g.preventDefault()},
ld:c})},vb=(a,b,c,d,e)=>{G.Nd||(G.Nd=L(257));return H({target:a,jd:e,md:d,nd:(k=event)=>{var g=G.Nd,l=document.pointerLockElement||document.yd||document.be||document.ae;r[g]=!!l;var m=l?.id||"";K(mb(l),g+1,128);K(m,g+129,128);J(d)(20,g,b)&&k.preventDefault()},ld:c})},wb=(a,b,c,d,e)=>H({target:a,jd:e,md:d,nd:(k=event)=>{J(d)(38,0,b)&&k.preventDefault()},ld:c}),xb=(a,b,c,d)=>{G.Sd||(G.Sd=L(36));a=I(a);return H({target:a,jd:"resize",md:d,nd:(e=event)=>{if(e.target==a){var k=document.body;if(k){var g=
G.Sd;u[g>>2]=0;u[g+4>>2]=k.clientWidth;u[g+8>>2]=k.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;J(d)(10,g,b)&&e.preventDefault()}}},ld:c})},yb=(a,b,c,d,e,k)=>{G.Rd||(G.Rd=L(1552));a=I(a);return H({target:a,Id:"touchstart"==k||"touchend"==k,jd:k,md:d,nd:g=>{var l={},m=g.touches;for(var p of m)p.$d=p.ee=0,l[p.identifier]=p;for(var w of g.changedTouches)w.$d=1,l[w.identifier]=w;for(var N of g.targetTouches)l[N.identifier].ee=
1;m=G.Rd;y[m>>3]=g.timeStamp;r[m+12]=g.ctrlKey;r[m+13]=g.shiftKey;r[m+14]=g.altKey;r[m+15]=g.metaKey;p=m+16;w=ob(a);N=0;for(let D of Object.values(l))if(l=p>>2,u[l]=D.identifier,u[l+1]=D.screenX,u[l+2]=D.screenY,u[l+3]=D.clientX,u[l+4]=D.clientY,u[l+5]=D.pageX,u[l+6]=D.pageY,r[p+28]=D.$d,r[p+29]=D.ee,u[l+8]=D.clientX-(w.left|0),u[l+9]=D.clientY-(w.top|0),p+=48,31<++N)break;u[m+8>>2]=N;J(d)(e,m,b)&&g.preventDefault()},ld:c})},M,zb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=
(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,g)=>b.drawElementsInstancedANGLE(c,d,e,k,g))},Ab=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Bb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,
d)=>b.drawBuffersWEBGL(c,d))},Cb=a=>{a.Fe=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Db=a=>{a.Ke=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},Eb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Fb=1,O=[],P=[],Gb=[],Hb=[],Q=[],R=[],Ib=[],Jb=[],S=[],Kb=[1,1,2,2,4,4,4,2,3,4,8],Lb={},Mb=4,Nb=0,Ob=a=>{for(var b=Fb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=M[c](),g=k&&Ob(d);k?(k.name=g,d[g]=k):T||=1282;u[b+4*e>>2]=g}},Pb=a=>{a=32-Math.clz32(0===a?0:a-1);var b=V.ud[a];if(b)return b;b=M.getParameter(34965);V.ud[a]=M.createBuffer();M.bindBuffer(34963,V.ud[a]);M.bufferData(34963,1<<a,35048);M.bindBuffer(34963,
b);return V.ud[a]},Rb=a=>{Qb=!1;for(var b=0;b<V.Md;++b){var c=V.td[b];if(c.Cd&&c.enabled){Qb=!0;var d=c.Pd;d=0<d?a*d:c.size*Kb[c.type-5120]*a;var e=32-Math.clz32(0===d?0:d-1);var k=V.vd[e],g=V.sd[e];V.sd[e]=V.sd[e]+1&63;var l=k[g];l?e=l:(l=M.getParameter(34964),k[g]=M.createBuffer(),M.bindBuffer(34962,k[g]),M.bufferData(34962,1<<e,35048),M.bindBuffer(34962,l),e=k[g]);M.bindBuffer(34962,e);M.bufferSubData(34962,0,t.subarray(c.Od,c.Od+d));c.pe.call(M,b,c.size,c.type,c.de,c.Pd,0)}}},Tb=(a,b)=>{a.yd||
(a.yd=a.getContext,a.getContext=function(d,e){e=a.yd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ce?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Sb(c,b):0},Sb=(a,b)=>{var c=Ob(Jb),d={handle:c,attributes:b,version:b.ce,Bd:a};a.canvas&&(a.canvas.ye=d);Jb[c]=d;("undefined"==typeof b.Yd||b.Yd)&&Ub(d);d.Md=d.Bd.getParameter(34921);d.td=[];for(a=0;a<d.Md;a++)d.td[a]={enabled:!1,Cd:!1,size:0,type:0,de:0,Pd:0,Od:0,pe:null};d.sd=[];d.Hd=[];d.sd.length=d.Hd.length=
22;d.vd=[];d.zd=[];d.vd.length=d.zd.length=22;d.ud=[];d.ud.length=22;for(a=0;21>=a;++a){d.ud[a]=null;d.sd[a]=d.Hd[a]=0;d.vd[a]=[];d.zd[a]=[];b=d.vd[a];var e=d.zd[a];b.length=e.length=64;for(var k=0;64>k;++k)b[k]=e[k]=null}return c},Ub=a=>{a||=V;if(!a.ve){a.ve=!0;var b=a.Bd;b.we=b.getExtension("WEBGL_multi_draw");b.ue=b.getExtension("EXT_polygon_offset_clamp");b.te=b.getExtension("EXT_clip_control");b.xe=b.getExtension("WEBGL_polygon_mode");zb(b);Ab(b);Bb(b);Cb(b);Db(b);2<=a.version&&(b.Xd=b.getExtension("EXT_disjoint_timer_query_webgl2"));
if(2>a.version||!b.Xd)b.Xd=b.getExtension("EXT_disjoint_timer_query");Eb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Qb,Vb=(a,b,c,d,e,k)=>{a={target:I(a),jd:k,md:d,nd:(g=event)=>{J(d)(e,0,b)&&g.preventDefault()},ld:c};H(a)},Wb=(a,b,c,d)=>{G.Ud||(G.Ud=L(96));return H({target:a,Id:!0,jd:"wheel",md:d,nd:(e=event)=>{var k=G.Ud;tb(k,e,a);y[k+64>>3]=e.deltaX;y[k+72>>3]=e.deltaY;y[k+80>>3]=e.deltaZ;u[k+88>>2]=e.deltaMode;J(d)(9,k,b)&&e.preventDefault()},ld:c})},
Xb=["default","low-power","high-performance"],Yb={},$b=()=>{if(!Zb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Yb)void 0===Yb[b]?delete a[b]:a[b]=Yb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Zb=c}return Zb},Zb,ac=[null,[],[]],bc=[],cc=()=>{var a=Eb(M);return a=a.concat(a.map(b=>"GL_"+b))},dc=(a,b)=>{if(b){var c=void 0;
switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=cc().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=M.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},ec=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},fc=a=>{var b=ec(a)+1,c=L(b);c&&K(a,c,b);return c},gc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),hc=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},ic=(a,b,c,d,e)=>{a=hc(a);b=d*((Nb||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Mb-1&-Mb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},W=a=>{var b=M.re;if(b){var c=b.Ad[a];"number"==typeof c&&(b.Ad[a]=c=M.getUniformLocation(b,b.ne[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],jc=[],C=a=>{var b=ec(a)+1,c=kc(b);K(a,c,b);return c},B=a=>{var b=lc();a();mc(b)};f.requestAnimationFrame=Xa;f.pauseMainLoop=ib;f.resumeMainLoop=function(){$a++;var a=Ra,b=Sa,c=Ta;Ta=null;hb(c,0,!1,ab,!0);Za(a,b);F()};f.preMainLoop&&fb.push(f.preMainLoop);f.postMainLoop&&gb.push(f.postMainLoop);
var nc=()=>{if(V){var a=V.vd;V.vd=V.zd;V.zd=a;a=V.sd;V.sd=V.Hd;V.Hd=a;for(a=0;21>=a;++a)V.sd[a]=0}};"undefined"!=typeof db&&fb.push(nc);for(var Y=0;32>Y;++Y)bc.push(Array(Y));var oc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=oc.subarray(0,Y);var pc=new Int32Array(288);for(Y=0;288>=Y;++Y)jc[Y]=pc.subarray(0,Y);
var Fc={ga:function(){return 0},ub:function(){return 0},vb:function(){},zb:()=>za(""),nb:()=>{Ha=!1;Ja=0},ob:(a,b)=>{Ka[a]&&(clearTimeout(Ka[a].id),delete Ka[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ka[a];Pa(()=>qc(a,performance.now()))},b);Ka[a]={id:c,Ue:b};return 0},U:function(a){if(void 0===window.localStorage)return 0;a=a?E(t,a):"";return(a=window.localStorage.getItem(a))?fc(a):0},lb:function(a,b){void 0!==window.localStorage&&(a=a?E(t,a):"",b=b?E(t,b):"",window.localStorage.setItem(a,
b))},hb:(a,b,c)=>{Qa.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Qa.push(112==d?v[c>>2]:106==d?ra[c>>3]:105==d?u[c>>2]:y[c>>3]);c+=e?8:4}return Ea[a](...Qa)},Lb:()=>{ib();Ta=null},yb:()=>Date.now(),na:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,za:(a,b,c)=>{a=I(a);if(!a)return-4;a=ob(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},y:()=>performance.now(),Mb:()=>performance.now(),fb:(a,b)=>{function c(d){J(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},
pb:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ta();var e=1;break a}catch(k){}e=void 0}if(e)return!0}return!1},P:(a,b,c,d)=>rb(a,b,c,d,12,"blur"),ma:(a,b,c)=>{a=I(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>rb(a,b,c,d,13,"focus"),_:(a,b,c,d)=>sb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>sb(a,b,c,d,1,"keypress"),
Z:(a,b,c,d)=>sb(a,b,c,d,3,"keyup"),gb:(a,b,c)=>{a=J(a);hb(a,b,c)},ea:(a,b,c,d)=>ub(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>ub(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>ub(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>ub(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>ub(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.yd||document.body.be||document.body.ae))return-1;a=I(a);if(!a)return-4;vb(a,b,c,d,"mozpointerlockchange");vb(a,b,c,d,"webkitpointerlockchange");
vb(a,b,c,d,"mspointerlockchange");return vb(a,b,c,d,"pointerlockchange")},R:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.yd||document.body.be||document.body.ae))return-1;a=I(a);if(!a)return-4;wb(a,b,c,d,"mozpointerlockerror");wb(a,b,c,d,"webkitpointerlockerror");wb(a,b,c,d,"mspointerlockerror");return wb(a,b,c,d,"pointerlockerror")},ua:(a,b,c,d)=>xb(a,b,c,d),T:(a,b,c,d)=>yb(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>yb(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>yb(a,b,c,d,24,"touchmove"),
X:(a,b,c,d)=>yb(a,b,c,d,22,"touchstart"),O:(a,b,c,d)=>{Vb(a,b,c,d,31,"webglcontextlost");return 0},N:(a,b,c,d)=>{Vb(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=I(a))?"undefined"!=typeof a.onwheel?Wb(a,b,c,d):-1:-4,Rb:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Xb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],ce:u[c+4],Me:u[c+5],Yd:r[b+24],se:r[b+25],Oe:u[c+7],Se:r[b+
32]};a=I(a);return!a||b.se?0:Tb(a,b)},tb:(a,b)=>{a=Jb[a];b=b?E(t,b):"";b.startsWith("GL_")&&(b=b.slice(3));"ANGLE_instanced_arrays"==b&&zb(M);"OES_vertex_array_object"==b&&Ab(M);"WEBGL_draw_buffers"==b&&Bb(M);"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Cb(M);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Db(M);"WEBGL_multi_draw"==b&&(M.we=M.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==b&&(M.ue=M.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&
(M.te=M.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(M.xe=M.getExtension("WEBGL_polygon_mode"));return!!a.Bd.getExtension(b)},Kb:a=>{V=Jb[a];f.ctx=M=V?.Bd;return!a||M?0:-5},wb:(a,b)=>{var c=0;$b().forEach((d,e)=>{var k=b+c;e=v[a+4*e>>2]=k;for(k=0;k<d.length;++k)r[e++]=d.charCodeAt(k);r[e]=0;c+=d.length+1});return 0},xb:(a,b)=>{var c=$b();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},fa:()=>52,sb:()=>52,qb:function(){return 70},rb:(a,b,c,d)=>{for(var e=0,k=
0;k<c;k++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=t[g+m],w=ac[a];0===p||10===p?((1===a?la:n)(E(w)),w.length=0):w.push(p)}e+=l}v[d>>2]=e;return 0},oc:function(a,b,c){const d=a?E(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(k){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+k)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var k=e.result;let g;try{g=k.transaction(["store"],
"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}k=g.objectStore("store");const l=d+"_"+b,m=k.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const w=rc(p);t.set(m.result,w);sc(c,w,p)}else sc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};g.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},
pc:function(a,b,c,d){const e=a?E(t,a):"";console.log("fs_js_save_snapshot: called with",e,b);let k;try{k=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+g);return}k.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");k.result.createObjectStore("store")};k.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const g=k.result.transaction(["store"],"readwrite");var l=g.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,
c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};g.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};k.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},o:a=>M.activeTexture(a),H:(a,b)=>{M.attachShader(P[a],R[b])},b:(a,b)=>{34962==a?M.wd=b:34963==a&&(M.xd=b);35051==a?M.Wd=b:35052==a&&(M.qd=b);M.bindBuffer(a,O[b])},a:(a,b,c)=>{M.bindBufferBase(a,b,O[c])},
i:(a,b)=>{M.bindFramebuffer(a,Gb[b])},Sa:(a,b)=>{M.bindRenderbuffer(a,Hb[b])},n:(a,b)=>{M.bindSampler(a,S[b])},d:(a,b)=>{M.bindTexture(a,Q[b])},M:a=>{M.bindVertexArray(Ib[a]);a=M.getParameter(34965);M.xd=a?a.name|0:0},ra:(a,b,c,d)=>M.blendColor(a,b,c,d),sa:(a,b)=>M.blendEquationSeparate(a,b),ta:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),Wb:(a,b,c,d,e,k,g,l,m,p)=>M.blitFramebuffer(a,b,c,d,e,k,g,l,m,p),Ua:(a,b,c,d)=>{2<=V.version?c&&b?M.bufferData(a,t,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?t.subarray(c,
c+b):b,d)},J:(a,b,c,d)=>{2<=V.version?c&&M.bufferSubData(a,b,t,d,c):M.bufferSubData(a,b,t.subarray(d,d+c))},C:a=>M.checkFramebufferStatus(a),nc:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),ya:(a,b,c)=>{M.clearBufferfv(a,b,x,c>>2)},mc:(a,b,c)=>{M.clearBufferiv(a,b,u,c>>2)},l:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Bb:a=>{M.compileShader(R[a])},Ka:(a,b,c,d,e,k,g,l)=>{2<=V.version?M.qd||!g?M.compressedTexImage2D(a,b,c,d,e,k,g,l):M.compressedTexImage2D(a,b,c,d,e,k,t,l,g):M.compressedTexImage2D(a,b,c,d,e,k,t.subarray(l,
l+g))},Ma:(a,b,c,d,e,k,g,l,m)=>{M.qd?M.compressedTexImage3D(a,b,c,d,e,k,g,l,m):M.compressedTexImage3D(a,b,c,d,e,k,g,t,m,l)},Fa:()=>{var a=Ob(P),b=M.createProgram();b.name=a;b.Fd=b.Dd=b.Ed=0;b.Td=1;P[a]=b;return a},Db:a=>{var b=Ob(R);R[b]=M.createShader(a);return b},qa:a=>M.cullFace(a),Eb:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=O[d];e&&(M.deleteBuffer(e),e.name=0,O[d]=null,d==M.wd&&(M.wd=0),d==M.xd&&(M.xd=0),d==M.Wd&&(M.Wd=0),d==M.qd&&(M.qd=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*
c>>2],e=Gb[d];e&&(M.deleteFramebuffer(e),e.name=0,Gb[d]=null)}},m:a=>{if(a){var b=P[a];b?(M.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},K:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Hb[d];e&&(M.deleteRenderbuffer(e),e.name=0,Hb[d]=null)}},q:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(M.deleteSampler(e),e.name=0,S[d]=null)}},u:a=>{if(a){var b=R[a];b?(M.deleteShader(b),R[a]=null):T||=1281}},L:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(M.deleteTexture(e),e.name=
0,Q[d]=null)}},Wa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];M.deleteVertexArray(Ib[d]);Ib[d]=null}},A:a=>M.depthFunc(a),r:a=>{M.depthMask(!!a)},e:a=>M.disable(a),oa:a=>{V.td[a].enabled=!1;M.disableVertexAttribArray(a)},Yb:(a,b,c)=>{Rb(b+c);M.drawArrays(a,b,c);Qb&&M.bindBuffer(34962,O[M.wd])},Zb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},B:(a,b)=>{for(var c=bc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];M.drawBuffers(c)},$b:(a,b,c,d)=>{var e=0;if(!M.xd){var k=1*Kb[c-5120]*b;var g=Pb(k);M.bindBuffer(34963,
g);M.bufferSubData(34963,0,t.subarray(d,d+k));if(0<b)for(g=0;g<V.Md;++g)if(k=V.td[g],k.Cd&&k.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:T||=1282;return}e=(new e(t.buffer,d,b)).reduce((l,m)=>Math.max(l,m))+1;break}d=0}Rb(e);M.drawElements(a,b,c,d);Qb&&M.bindBuffer(34962,O[M.wd]);M.xd||M.bindBuffer(34963,null)},_b:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},h:a=>M.enable(a),jc:a=>{V.td[a].enabled=!0;M.enableVertexAttribArray(a)},
D:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,Hb[d])},k:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,Q[d],e)},t:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,Q[c],d,e)},pa:a=>M.frontFace(a),Va:(a,b)=>{U(a,b,"createBuffer",O)},E:(a,b)=>{U(a,b,"createFramebuffer",Gb)},Ta:(a,b)=>{U(a,b,"createRenderbuffer",Hb)},Ha:(a,b)=>{U(a,b,"createSampler",S)},Qa:(a,b)=>{U(a,b,"createTexture",Q)},Za:(a,b)=>{U(a,b,"createVertexArray",Ib)},Ba:(a,b)=>M.getAttribLocation(P[a],b?E(t,b):""),c:(a,b)=>dc(a,b),Da:(a,b,c,d)=>
{a=M.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(u[c>>2]=b)},G:(a,b,c)=>{if(c)if(a>=Fb)T||=1281;else if(a=P[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Fd){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Fd=Math.max(a.Fd,M.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Fd}else if(35722==b){if(!a.Dd)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.Dd=Math.max(a.Dd,M.getActiveAttrib(a,b).name.length+
1);u[c>>2]=a.Dd}else if(35381==b){if(!a.Ed)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Ed=Math.max(a.Ed,M.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Ed}else u[c>>2]=M.getProgramParameter(a,b);else T||=1281},Ab:(a,b,c,d)=>{a=M.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?K(a,d,b):0;c&&(u[c>>2]=b)},ia:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>
2]=M.getShaderParameter(R[a],b):T||=1281},_a:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Lb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=cc().map(fc),c=Lb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},F:(a,b)=>{b=b?E(t,b):"";if(a=P[a]){var c=a,d=c.Ad,e=c.oe,k;if(!d){c.Ad=d={};c.ne={};var g=M.getProgramParameter(c,35718);for(k=0;k<g;++k){var l=M.getActiveUniform(c,k);var m=l.name;l=l.size;var p=gc(m);p=0<p?m.slice(0,p):m;var w=c.Td;c.Td+=l;
e[p]=[l,w];for(m=0;m<l;++m)d[w]=m,c.ne[w++]=p}}c=a.Ad;d=0;e=b;k=gc(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.oe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else T||=1281;return-1},Vb:(a,b,c)=>{for(var d=bc[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];M.invalidateFramebuffer(a,d)},Ea:a=>{a=P[a];M.linkProgram(a);a.Ad=0;a.oe={}},Ya:(a,b)=>{3317==a?Mb=b:3314==a&&(Nb=b);M.pixelStorei(a,b)},xa:(a,b)=>M.polygonOffset(a,b),Xb:a=>M.readBuffer(a),Ra:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,
b,c,d,e),I:(a,b,c)=>{M.samplerParameterf(S[a],b,c)},g:(a,b,c)=>{M.samplerParameteri(S[a],b,c)},s:(a,b,c,d)=>M.scissor(a,b,c,d),Cb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var g=(g=v[c+4*k>>2])?E(t,g,d?v[d+4*k>>2]:void 0):"";e+=g}M.shaderSource(R[a],e)},Gb:(a,b,c)=>M.stencilFunc(a,b,c),wa:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),z:a=>M.stencilMask(a),Fb:(a,b,c)=>M.stencilOp(a,b,c),va:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),Ja:(a,b,c,d,e,k,g,l,m)=>{if(2<=V.version){if(M.qd){M.texImage2D(a,b,c,d,e,k,g,
l,m);return}if(m){var p=hc(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);M.texImage2D(a,b,c,d,e,k,g,l,p,m);return}}p=m?ic(l,g,d,e,m):null;M.texImage2D(a,b,c,d,e,k,g,l,p)},La:(a,b,c,d,e,k,g,l,m,p)=>{if(M.qd)M.texImage3D(a,b,c,d,e,k,g,l,m,p);else if(p){var w=hc(m);M.texImage3D(a,b,c,d,e,k,g,l,m,w,p>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else M.texImage3D(a,b,c,d,e,k,g,l,m,null)},Oa:(a,b,c)=>M.texParameteri(a,b,c),Ia:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Na:(a,b,c,d,e,k)=>M.texStorage3D(a,b,c,d,e,k),Tb:(a,
b,c,d,e,k,g,l,m)=>{if(2<=V.version){if(M.qd){M.texSubImage2D(a,b,c,d,e,k,g,l,m);return}if(m){var p=hc(l);M.texSubImage2D(a,b,c,d,e,k,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}m=m?ic(l,g,e,k,m):null;M.texSubImage2D(a,b,c,d,e,k,g,l,m)},Ub:(a,b,c,d,e,k,g,l,m,p,w)=>{if(M.qd)M.texSubImage3D(a,b,c,d,e,k,g,l,m,p,w);else if(w){var N=hc(p);M.texSubImage3D(a,b,c,d,e,k,g,l,m,p,N,w>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,k,g,l,m,p,null)},ic:(a,b,c)=>{if(2<=V.version)b&&
M.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);M.uniform1fv(W(a),d)}},Ca:(a,b)=>{M.uniform1i(W(a),b)},ec:(a,b,c)=>{if(2<=V.version)b&&M.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=jc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);M.uniform1iv(W(a),d)}},hc:(a,b,c)=>{if(2<=V.version)b&&M.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=
x.subarray(c>>2,c+8*b>>2);M.uniform2fv(W(a),d)}},dc:(a,b,c)=>{if(2<=V.version)b&&M.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=jc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);M.uniform2iv(W(a),d)}},gc:(a,b,c)=>{if(2<=V.version)b&&M.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);M.uniform3fv(W(a),d)}},cc:(a,b,c)=>{if(2<=
V.version)b&&M.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=jc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);M.uniform3iv(W(a),d)}},fc:(a,b,c)=>{if(2<=V.version)b&&M.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var k=0;k<b;k+=4){var g=c+k;d[k]=e[g];d[k+1]=e[g+1];d[k+2]=e[g+2];d[k+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);M.uniform4fv(W(a),d)}},bc:(a,b,c)=>{if(2<=V.version)b&&M.uniform4iv(W(a),
u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=jc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);M.uniform4iv(W(a),d)}},ac:(a,b,c,d)=>{if(2<=V.version)b&&M.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],k=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=k[l];e[g+1]=k[l+1];e[g+2]=k[l+2];e[g+3]=k[l+3];e[g+4]=k[l+4];e[g+5]=k[l+5];e[g+6]=k[l+6];e[g+7]=k[l+7];e[g+8]=k[l+8];e[g+9]=k[l+9];e[g+10]=
k[l+10];e[g+11]=k[l+11];e[g+12]=k[l+12];e[g+13]=k[l+13];e[g+14]=k[l+14];e[g+15]=k[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(W(a),!!c,e)}},j:a=>{a=P[a];M.useProgram(a);M.re=a},kc:(a,b)=>{M.vertexAttribDivisor(a,b)},lc:(a,b,c,d,e,k)=>{var g=V.td[a];M.wd?(g.Cd=!1,M.vertexAttribPointer(a,b,c,!!d,e,k)):(g.size=b,g.type=c,g.de=d,g.Pd=e,g.Od=k,g.Cd=!0,g.pe=function(l,m,p,w,N,D){this.vertexAttribPointer(l,m,p,w,N,D)})},p:(a,b,c,d)=>M.viewport(a,b,c,d),mb:Ma,kb:function(){f.ge=a=>{0!=tc()&&
(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.ge)},jb:function(){f.me=a=>{const b=a.clipboardData.getData("text");B(()=>{const c=C(b);uc(c)})};window.addEventListener("paste",f.me)},ib:function(){f.Te=[];f.he=b=>{b.stopPropagation();b.preventDefault()};f.ie=b=>{b.stopPropagation();b.preventDefault()};f.je=b=>{b.stopPropagation();b.preventDefault()};f.ke=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.le=c;vc(c.length);for(let e=0;e<c.length;e++)B(()=>
{const k=C(c[e].name);wc(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);xc(b.clientX,b.clientY,d)};const a=f.od;a.addEventListener("dragenter",f.he,!1);a.addEventListener("dragleave",f.ie,!1);a.addEventListener("dragover",f.je,!1);a.addEventListener("drop",f.ke,!1)},cb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ab:function(a){const b=f.le;return 0>a||a>=b.length?0:b[a].size},$a:function(a,b,c,d,e){const k=
new FileReader;k.onload=g=>{g=g.target.result;g.byteLength>d?yc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(g),c),yc(a,1,0,b,g.byteLength,c,d,e))};k.onerror=()=>{yc(a,0,2,b,0,c,d,e)};k.readAsArrayBuffer(f.le[a])},Aa:function(a,b){0!==b&&(document.title=b?E(t,b):"");a=a?E(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?nb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.od=I(a);f.od||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.od.requestPointerLock||
console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Jb:function(){window.removeEventListener("beforeunload",f.ge)},Ib:function(){window.removeEventListener("paste",f.me)},Hb:function(){const a=f.od;a.removeEventListener("dragenter",f.he);a.removeEventListener("dragleave",f.ie);a.removeEventListener("dragover",f.je);a.removeEventListener("drop",f.ke)},w:function(){f.od&&f.od.requestPointerLock&&f.od.requestPointerLock()},eb:function(a,b){if(f.od){if(0===b)a="none";else switch(a){case 0:a=
"auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.od.style.cursor=a}},bb:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,
0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},db:function(a){a=a?E(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");
document.body.removeChild(b)},Nb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){const c=b.value[0],d=b.value[1];B(()=>{const e=C(c),k=C(d);zc(e,k)})}},Pb:function(){return f.pd?f.pd.bufferSize:0},Sb:function(a,b,c){f.hd=null;f.pd=null;"undefined"!==typeof AudioContext?f.hd=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.hd=null,console.log("sokol_audio.h: no WebAudio support"));return f.hd?(console.log("sokol_audio.h: sample rate ",
f.hd.sampleRate),f.pd=f.hd.createScriptProcessor(c,0,b),f.pd.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Ac(e);if(k){const g=d.outputBuffer.numberOfChannels;for(let l=0;l<g;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(k>>2)+(g*p+l)]}}},f.pd.connect(f.hd.destination),a=()=>{f.hd&&"suspended"===f.hd.state&&f.hd.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),
1):0},Qb:function(){return f.hd?f.hd.sampleRate:0},la:function(){const a=f.hd;null!==a&&(f.pd&&f.pd.disconnect(),a.close(),f.hd=null,f.pd=null)},Ob:function(){if(f.hd)return"suspended"===f.hd.state?1:0},x:function(a,b,c,d,e,k){b=b?E(t,b):"";const g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";const l=0<d;l&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(g.readyState==XMLHttpRequest.DONE)if(206==g.status||200==g.status&&!l){const m=new Uint8Array(g.response),
p=m.length;p<=k?(t.set(m,e),Bc(a,d,p)):Cc(a)}else Dc(a,g.status)};g.send()},ka:function(a,b){b=b?E(t,b):"";const c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(c.readyState==XMLHttpRequest.DONE)if(200==c.status){const d=c.getResponseHeader("Content-Length");Ec(a,d)}else Dc(a,c.status)};c.send()},ha:function(){return navigator.userAgent.includes("Macintosh")?1:0},ja:function(a,b){b=b?E(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);
break;default:console.info(b)}},Xa:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Pa:function(){console.log("webapi_js_event_reboot()");f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},Ga:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},v:function(a,b){console.log("webapi_js_event_stopped()");
f.webapi_onStopped?f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z;
(async function(){function a(c){Z=c.exports;na=Z.qc;ta();qb=Z.vc;va.unshift(Z.rc);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:Fc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=sa("emu.wasm")?"emu.wasm":f.locateFile?f.locateFile("emu.wasm",h):h+"emu.wasm";return a((await Da(b)).instance)})();
var rc=f._fs_emsc_alloc=a=>(rc=f._fs_emsc_alloc=Z.sc)(a),L=a=>(L=Z.tc)(a),sc=f._fs_emsc_load_snapshot_callback=(a,b,c)=>(sc=f._fs_emsc_load_snapshot_callback=Z.uc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.wc)();f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.xc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.yc)(a);f._webapi_free=a=>(f._webapi_free=Z.zc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.Ac)();f._webapi_reset=()=>(f._webapi_reset=Z.Bc)();
f._webapi_ready=()=>(f._webapi_ready=Z.Cc)();f._webapi_load=(a,b)=>(f._webapi_load=Z.Dc)(a,b);f._webapi_load_file_internal=a=>(f._webapi_load_file_internal=Z.Ec)(a);f._webapi_unload_file=()=>(f._webapi_unload_file=Z.Fc)();f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z.Gc)(a);f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.Hc)(a);f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.Ic)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.Jc)(a);
f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.Kc)();f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.Lc)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.Mc)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.Nc)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.Oc)();f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.Pc)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.Qc)(a,b);
f._webapi_input_internal=a=>(f._webapi_input_internal=Z.Rc)(a);
var uc=f.__sapp_emsc_onpaste=a=>(uc=f.__sapp_emsc_onpaste=Z.Sc)(a),tc=f.__sapp_html5_get_ask_leave_site=()=>(tc=f.__sapp_html5_get_ask_leave_site=Z.Tc)(),vc=f.__sapp_emsc_begin_drop=a=>(vc=f.__sapp_emsc_begin_drop=Z.Uc)(a),wc=f.__sapp_emsc_drop=(a,b)=>(wc=f.__sapp_emsc_drop=Z.Vc)(a,b),xc=f.__sapp_emsc_end_drop=(a,b,c)=>(xc=f.__sapp_emsc_end_drop=Z.Wc)(a,b,c),yc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,k,g,l)=>(yc=f.__sapp_emsc_invoke_fetch_cb=Z.Xc)(a,b,c,d,e,k,g,l),Gc=f._main=(a,b)=>(Gc=f._main=Z.Yc)(a,
b),Ac=f.__saudio_emsc_pull=a=>(Ac=f.__saudio_emsc_pull=Z.Zc)(a),zc=f.__sargs_add_kvp=(a,b)=>(zc=f.__sargs_add_kvp=Z._c)(a,b),Ec=f.__sfetch_emsc_head_response=(a,b)=>(Ec=f.__sfetch_emsc_head_response=Z.$c)(a,b),Bc=f.__sfetch_emsc_get_response=(a,b,c)=>(Bc=f.__sfetch_emsc_get_response=Z.ad)(a,b,c),Dc=f.__sfetch_emsc_failed_http_status=(a,b)=>(Dc=f.__sfetch_emsc_failed_http_status=Z.bd)(a,b),Cc=f.__sfetch_emsc_failed_buffer_too_small=a=>(Cc=f.__sfetch_emsc_failed_buffer_too_small=Z.cd)(a),qc=(a,b)=>
(qc=Z.dd)(a,b),mc=a=>(mc=Z.ed)(a),kc=a=>(kc=Z.fd)(a),lc=()=>(lc=Z.gd)();function Hc(a=[]){var b=Gc;a.unshift(fa);var c=a.length,d=kc(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=C(g);e+=4});v[e>>2]=0;try{var k=b(c,d);Na(k)}catch(g){La(g)}}
function Ic(a=ea){function b(){f.calledRun=!0;if(!q){Ga(va);Ga(wa);f.onRuntimeInitialized?.();f.noInitialRun||Hc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ga(xa)}}if(0<z)A=Ic;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ga(ua);0<z?A=Ic:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Ic();
