var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},f),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=f.print||console.log.bind(console),n=f.printErr||console.error.bind(console);Object.assign(f,da);da=null;f.arguments&&(ea=f.arguments);f.thisProgram&&(fa=f.thisProgram);var ma=f.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,x,ra,y,sa=a=>a.startsWith("data:application/octet-stream;base64,"),ka=a=>a.startsWith("file://");
function ta(){var a=na.buffer;f.HEAP8=r=new Int8Array(a);f.HEAP16=pa=new Int16Array(a);f.HEAPU8=t=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAP32=u=new Int32Array(a);f.HEAPU32=v=new Uint32Array(a);f.HEAPF32=x=new Float32Array(a);f.HEAPF64=y=new Float64Array(a);f.HEAP64=ra=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ua.unshift(a)}var z=0,A=null;
function za(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==Aa&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!(ma||"function"!=typeof WebAssembly.instantiateStreaming||sa(b)||ka(b)||ca))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
var Ea={575997:()=>{f._webapi_input=a=>{B(()=>f._webapi_input_internal(C(a)))};f._webapi_load_file=a=>{B(()=>f._webapi_load_file_internal(C(a)))}}};class Fa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ga=a=>{for(;0<a.length;)a.shift()(f)},Ha=f.noExitRuntime||!0,Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ja=0,Ka={},La=a=>{a instanceof Fa||"unwind"==a||ha(1,a)},Ma=a=>{oa=a;Ha||0<Ja||(f.onExit?.(a),q=!0);ha(a,new Fa(a))},Na=a=>{oa=a;Ma(a)},Oa=()=>{if(!(Ha||0<Ja))try{var a=oa;oa=a;Ma(a)}catch(b){La(b)}},Pa=a=>{if(!q)try{a(),Oa()}catch(b){La(b)}},F=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=
c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-e},Qa=[],Za=(a,b)=>{Ra=a;Sa=b;if(Ta)if(Ua||=!0,0==a)G=function(){setTimeout(Va,Math.max(0,Wa+b-performance.now())|0)};else if(1==a)G=function(){Xa(Va)};else if(2==a){if("undefined"==typeof Ya)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===
d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ya=d=>{c.push(d);if(ba){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ya=setImmediate;G=function(){Ya(Va)}}},hb=(a,b,c,d,e)=>{function g(){return h<$a?(Oa(),!1):!0}Ta=a;ab=d;var h=$a;Ua=!1;Va=function(){if(!q)if(0<bb.length){var l=bb.shift();l.Ge(l.ve);if(cb){var m=cb,p=0==m%1?m-1:Math.floor(m);cb=l.xe?p:(8*m+(p+.5))/
9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=cb??0,p=db.Ce??0,m?m<p?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));g()&&setTimeout(Va,0)}else if(g())if(eb=eb+1|0,1==Ra&&1<Sa&&0!=eb%Sa)G();else{0==Ra&&(Wa=performance.now());a:if(!q){for(l of fb)if(!1===l())break a;Pa(a);for(m of gb)m()}g()&&G()}};e||(0<b?Za(0,1E3/b):Za(1,1),G());if(c)throw"unwind";},Ua=!1,G=null,$a=0,Ta=null,ab=0,Ra=0,Sa=0,eb=0,bb=[],fb=[],gb=[];function ib(){G=null;$a++}
var jb=0;function Xa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===jb)jb=b+1E3/60;else for(;b+2>=jb;)jb+=1E3/60;setTimeout(a,Math.max(jb-b,0))}}var db={},Wa,Va,Ya,cb;function kb(a){var b=I.kd[a];b.target.removeEventListener(b.jd,b.ae,b.ld);I.kd.splice(a,1)}function lb(){if(navigator.userActivation?navigator.userActivation.isActive:I.Md&&I.qe.Kd){var a=I.qd;I.qd=[];for(var b of a)b.Rd(...b.Xd)}}
function J(a){if(!a.target)return-4;if(a.md)a.ae=function(c){++I.Md;I.qe=a;lb();a.nd(c);lb();--I.Md},a.target.addEventListener(a.jd,a.ae,a.ld),I.kd.push(a);else for(var b=0;b<I.kd.length;++b)I.kd[b].target==a.target&&I.kd[b].jd==a.jd&&kb(b--);return 0}function mb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={we:0,He:0,Nd:0,Fd:0,Wd:0,Td:0,Ld:0,Ae:0,Me:0,ze:0,Fe:0,Qd:0,Ue:0,Sd:0,Je(a,b,c){r.set(r.subarray(b,b+c),a)},Oe(){for(;I.kd.length;)kb(I.kd.length-1);I.qd=[]},Md:0,qd:[],ye(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var l in g)if(g[l]!=h[l])return!1;return!0}for(var e of I.qd)if(e.Rd==a&&d(e.Xd,c))return;I.qd.push({Rd:a,ge:b,Xd:c});I.qd.sort((g,h)=>g.ge<h.ge)},Qe(a){I.qd=I.qd.filter(b=>b.Rd!=a)},kd:[],Pe:(a,b)=>{for(var c=0;c<I.kd.length;++c)I.kd[c].target!=a||b&&b!=I.kd[c].jd||
kb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},nb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?D(t,a):"":a;return nb[a]||("undefined"!=typeof document?document.querySelector(a):null)},ob=a=>0>nb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},pb=[],qb,L=a=>{var b=pb[a];b||(a>=pb.length&&(pb.length=a+1),pb[a]=b=qb.get(a));return b},rb=(a,b,c,d,e,g)=>{I.Ld||(I.Ld=M(256));a={target:K(a),jd:g,md:d,
nd:(h=event)=>{var l=h.target.id?h.target.id:"",m=I.Ld;F(mb(h.target),m+0,128);F(l,m+128,128);L(d)(e,m,b)&&h.preventDefault()},ld:c};return J(a)},sb=(a,b,c,d,e,g)=>{I.Nd||(I.Nd=M(160));a={target:K(a),jd:g,md:d,nd:h=>{var l=I.Nd;y[l>>3]=h.timeStamp;var m=l>>2;u[m+2]=h.location;r[l+12]=h.ctrlKey;r[l+13]=h.shiftKey;r[l+14]=h.altKey;r[l+15]=h.metaKey;r[l+16]=h.repeat;u[m+5]=h.charCode;u[m+6]=h.keyCode;u[m+7]=h.which;F(h.key||"",l+32,32);F(h.code||"",l+64,32);F(h.char||"",l+96,32);F(h.locale||"",l+128,
32);L(d)(e,l,b)&&h.preventDefault()},ld:c};return J(a)},tb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=ob(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},ub=(a,b,c,d,e,g)=>{I.Fd||(I.Fd=M(64));a=K(a);return J({target:a,Kd:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,
jd:g,md:d,nd:(h=event)=>{tb(I.Fd,h,a);L(d)(e,I.Fd,b)&&h.preventDefault()},ld:c})},vb=(a,b,c,d,e)=>{I.Qd||(I.Qd=M(257));return J({target:a,jd:e,md:d,nd:(g=event)=>{var h=I.Qd,l=document.pointerLockElement||document.zd||document.de||document.ce;r[h]=!!l;var m=l?.id||"";F(mb(l),h+1,128);F(m,h+129,128);L(d)(20,h,b)&&g.preventDefault()},ld:c})},wb=(a,b,c,d,e)=>J({target:a,jd:e,md:d,nd:(g=event)=>{L(d)(38,0,b)&&g.preventDefault()},ld:c}),xb=(a,b,c,d)=>{I.Td||(I.Td=M(36));a=K(a);return J({target:a,jd:"resize",
md:d,nd:(e=event)=>{if(e.target==a){var g=document.body;if(g){var h=I.Td;u[h>>2]=0;u[h+4>>2]=g.clientWidth;u[h+8>>2]=g.clientHeight;u[h+12>>2]=innerWidth;u[h+16>>2]=innerHeight;u[h+20>>2]=outerWidth;u[h+24>>2]=outerHeight;u[h+28>>2]=pageXOffset|0;u[h+32>>2]=pageYOffset|0;L(d)(10,h,b)&&e.preventDefault()}}},ld:c})},yb=(a,b,c,d,e,g)=>{I.Sd||(I.Sd=M(1552));a=K(a);return J({target:a,Kd:"touchstart"==g||"touchend"==g,jd:g,md:d,nd:h=>{var l={},m=h.touches;for(var p of m)p.be=p.fe=0,l[p.identifier]=p;for(var w of h.changedTouches)w.be=
1,l[w.identifier]=w;for(var H of h.targetTouches)l[H.identifier].fe=1;m=I.Sd;y[m>>3]=h.timeStamp;r[m+12]=h.ctrlKey;r[m+13]=h.shiftKey;r[m+14]=h.altKey;r[m+15]=h.metaKey;p=m+16;w=ob(a);H=0;for(let E of Object.values(l))if(l=p>>2,u[l]=E.identifier,u[l+1]=E.screenX,u[l+2]=E.screenY,u[l+3]=E.clientX,u[l+4]=E.clientY,u[l+5]=E.pageX,u[l+6]=E.pageY,r[p+28]=E.be,r[p+29]=E.fe,u[l+8]=E.clientX-(w.left|0),u[l+9]=E.clientY-(w.top|0),p+=48,31<++H)break;u[m+8>>2]=H;L(d)(e,m,b)&&h.preventDefault()},ld:c})},N,zb=
a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,g)=>b.drawArraysInstancedANGLE(c,d,e,g),a.drawElementsInstanced=(c,d,e,g,h)=>b.drawElementsInstancedANGLE(c,d,e,g,h))},Ab=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
Bb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Cb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Db=1,O=[],P=[],Eb=[],Fb=[],Q=[],R=[],Gb=[],Hb=[],S=[],Ib=[1,1,2,2,4,4,4,2,3,4,8],Jb={},Kb=4,Lb=0,Mb=a=>{for(var b=Db++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=N[c](),h=g&&Mb(d);g?(g.name=h,d[h]=g):T||=1282;u[b+4*e>>2]=h}},Nb=a=>{a=32-Math.clz32(0===a?0:a-1);var b=V.wd[a];if(b)return b;b=N.getParameter(34965);V.wd[a]=N.createBuffer();N.bindBuffer(34963,V.wd[a]);N.bufferData(34963,1<<a,35048);N.bindBuffer(34963,
b);return V.wd[a]},Pb=a=>{Ob=!1;for(var b=0;b<V.Od;++b){var c=V.sd[b];if(c.td&&c.enabled){Ob=!0;var d=c.Hd;d=0<d?a*d:c.size*Ib[c.type-5120]*a;var e=32-Math.clz32(0===d?0:d-1);var g=V.xd[e],h=V.rd[e];V.rd[e]=V.rd[e]+1&63;var l=g[h];l?e=l:(l=N.getParameter(34964),g[h]=N.createBuffer(),N.bindBuffer(34962,g[h]),N.bufferData(34962,1<<e,35048),N.bindBuffer(34962,l),e=g[h]);N.bindBuffer(34962,e);N.bufferSubData(34962,0,t.subarray(c.Gd,c.Gd+d));c.Vd.call(N,b,c.size,c.type,c.Pd,c.Hd,0)}}},Rb=(a,b)=>{a.zd||
(a.zd=a.getContext,a.getContext=function(d,e){e=a.zd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ee?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Qb(c,b):0},Qb=(a,b)=>{var c=Mb(Hb),d={handle:c,attributes:b,version:b.ee,Jd:a};a.canvas&&(a.canvas.ue=d);Hb[c]=d;("undefined"==typeof b.$d||b.$d)&&Sb(d);d.Od=d.Jd.getParameter(34921);d.sd=[];for(a=0;a<d.Od;a++)d.sd[a]={enabled:!1,td:!1,size:0,type:0,Pd:0,Hd:0,Gd:0,Vd:null};d.rd=[];d.Id=[];d.rd.length=d.Id.length=
22;d.xd=[];d.Ad=[];d.xd.length=d.Ad.length=22;d.wd=[];d.wd.length=22;for(a=0;21>=a;++a){d.wd[a]=null;d.rd[a]=d.Id[a]=0;d.xd[a]=[];d.Ad[a]=[];b=d.xd[a];var e=d.Ad[a];b.length=e.length=64;for(var g=0;64>g;++g)b[g]=e[g]=null}return c},Sb=a=>{a||=V;if(!a.te){a.te=!0;var b=a.Jd;b.Le=b.getExtension("WEBGL_multi_draw");b.Ee=b.getExtension("EXT_polygon_offset_clamp");b.De=b.getExtension("EXT_clip_control");b.Ve=b.getExtension("WEBGL_polygon_mode");zb(b);Ab(b);Bb(b);b.Be=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.Ie=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Zd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Zd)b.Zd=b.getExtension("EXT_disjoint_timer_query");Cb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Ob,Tb=(a,b,c,d,e,g)=>{a={target:K(a),jd:g,md:d,nd:(h=event)=>{L(d)(e,0,b)&&h.preventDefault()},ld:c};J(a)},Ub=(a,b,c,d)=>{I.Wd||(I.Wd=M(96));return J({target:a,Kd:!0,jd:"wheel",md:d,nd:(e=event)=>
{var g=I.Wd;tb(g,e,a);y[g+64>>3]=e.deltaX;y[g+72>>3]=e.deltaY;y[g+80>>3]=e.deltaZ;u[g+88>>2]=e.deltaMode;L(d)(9,g,b)&&e.preventDefault()},ld:c})},Vb=["default","low-power","high-performance"],Wb={},Yb=()=>{if(!Xb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Wb)void 0===Wb[b]?delete a[b]:a[b]=Wb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Xb=c}return Xb},Xb,Zb=[null,[],[]],$b=[],ac=()=>{var a=Cb(N);return a=a.concat(a.map(b=>"GL_"+b))},bc=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=ac().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;
case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);
return}}break;default:T||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else T||=1281},cc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},dc=a=>{var b=cc(a)+1,c=M(b);c&&F(a,c,b);return c},ec=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),fc=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?v:qa},W=a=>{var b=N.re;if(b){var c=b.Bd[a];"number"==typeof c&&(b.Bd[a]=c=N.getUniformLocation(b,b.oe[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],gc=[],C=a=>{var b=cc(a)+1,c=hc(b);F(a,c,b);return c},B=a=>{var b=ic();a();jc(b)};f.requestAnimationFrame=Xa;f.pauseMainLoop=ib;f.resumeMainLoop=function(){$a++;var a=Ra,b=Sa,c=Ta;Ta=null;hb(c,0,!1,ab,!0);Za(a,b);G()};f.preMainLoop&&fb.push(f.preMainLoop);f.postMainLoop&&gb.push(f.postMainLoop);
var kc=()=>{if(V){var a=V.xd;V.xd=V.Ad;V.Ad=a;a=V.rd;V.rd=V.Id;V.Id=a;for(a=0;21>=a;++a)V.rd[a]=0}};"undefined"!=typeof db&&fb.push(kc);for(var Y=0;32>Y;++Y)$b.push(Array(Y));var lc=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=lc.subarray(0,Y);var mc=new Int32Array(288);for(Y=0;288>=Y;++Y)gc[Y]=mc.subarray(0,Y);
var Dc={ja:function(){return 0},tb:function(){return 0},ub:function(){},zb:()=>za(""),mb:()=>{Ha=!1;Ja=0},nb:(a,b)=>{Ka[a]&&(clearTimeout(Ka[a].id),delete Ka[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ka[a];Pa(()=>nc(a,performance.now()))},b);Ka[a]={id:c,Te:b};return 0},ob:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(g,e);u[b>>2]=Number(g!=e);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/
60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(F(a,c,17),F(b,d,17)):(F(a,d,17),F(b,c,17))},yb:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},W:function(a){if(void 0===window.localStorage)return 0;a=a?D(t,a):"";return(a=window.localStorage.getItem(a))?dc(a):0},kb:function(a,b){void 0!==window.localStorage&&(a=a?D(t,a):"",b=b?D(t,b):"",window.localStorage.setItem(a,b))},fb:(a,b,c)=>{Qa.length=0;for(var d;d=
t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Qa.push(112==d?v[c>>2]:106==d?ra[c>>3]:105==d?u[c>>2]:y[c>>3]);c+=e?8:4}return Ea[a](...Qa)},Lb:()=>{ib();Ta=null},xb:()=>Date.now(),qa:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,Ca:(a,b,c)=>{a=K(a);if(!a)return-4;a=ob(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},C:()=>performance.now(),Mb:()=>performance.now(),eb:(a,b)=>{function c(d){L(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},pb:a=>{var b=t.length;a>>>=0;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ta();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>rb(a,b,c,d,12,"blur"),pa:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>rb(a,b,c,d,13,"focus"),ba:(a,b,c,d)=>sb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>sb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>sb(a,b,c,d,3,"keyup"),
gb:(a,b,c)=>{a=L(a);hb(a,b,c)},ia:(a,b,c,d)=>ub(a,b,c,d,5,"mousedown"),ea:(a,b,c,d)=>ub(a,b,c,d,33,"mouseenter"),da:(a,b,c,d)=>ub(a,b,c,d,34,"mouseleave"),fa:(a,b,c,d)=>ub(a,b,c,d,8,"mousemove"),ga:(a,b,c,d)=>ub(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.zd||document.body.de||document.body.ce))return-1;a=K(a);if(!a)return-4;vb(a,b,c,d,"mozpointerlockchange");vb(a,b,c,d,"webkitpointerlockchange");vb(a,b,c,d,"mspointerlockchange");
return vb(a,b,c,d,"pointerlockchange")},U:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.zd||document.body.de||document.body.ce))return-1;a=K(a);if(!a)return-4;wb(a,b,c,d,"mozpointerlockerror");wb(a,b,c,d,"webkitpointerlockerror");wb(a,b,c,d,"mspointerlockerror");return wb(a,b,c,d,"pointerlockerror")},va:(a,b,c,d)=>xb(a,b,c,d),X:(a,b,c,d)=>yb(a,b,c,d,25,"touchcancel"),Y:(a,b,c,d)=>yb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>yb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>yb(a,b,c,
d,22,"touchstart"),R:(a,b,c,d)=>{Tb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{Tb(a,b,c,d,32,"webglcontextrestored");return 0},ca:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Ub(a,b,c,d):-1:-4,Pb:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Vb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],ee:u[c+4],Ke:u[c+5],$d:r[b+24],se:r[b+25],Ne:u[c+7],Re:r[b+32]};a=K(a);return!a||
b.se?0:Rb(a,b)},Hb:a=>{V=Hb[a];f.ctx=N=V?.Jd;return!a||N?0:-5},vb:(a,b)=>{var c=0;Yb().forEach((d,e)=>{var g=b+c;e=v[a+4*e>>2]=g;for(g=0;g<d.length;++g)r[e++]=d.charCodeAt(g);r[e]=0;c+=d.length+1});return 0},wb:(a,b)=>{var c=Yb();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0},ha:()=>52,sb:()=>52,qb:function(){return 70},rb:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=v[b>>2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=t[h+m],w=Zb[a];0===p||10===p?((1===a?la:n)(D(w)),w.length=
0):w.push(p)}e+=l}v[d>>2]=e;return 0},nc:function(a,b,c){const d=a?D(t,a):"";let e;try{e=window.indexedDB.open("chips",1)}catch(g){console.log("fs_js_load_snapshot: failed to open IndexedDB with "+g)}e.onupgradeneeded=()=>{console.log("fs_js_load_snapshot: creating db");e.result.createObjectStore("store")};e.onsuccess=()=>{var g=e.result;let h;try{h=g.transaction(["store"],"readwrite")}catch(p){console.log("fs_js_load_snapshot: db.transaction failed with",p);return}g=h.objectStore("store");const l=
d+"_"+b,m=g.get(l);m.onsuccess=()=>{if(void 0!==m.result){const p=m.result.length;console.log("fs_js_load_snapshot:",l,"successfully loaded",p,"bytes");const w=oc(p);t.set(m.result,w);pc(c,w,p)}else pc(c,0,0)};m.onerror=()=>{console.log("fs_js_load_snapshot: FAILED loading",l)};h.onerror=()=>{console.log("fs_js_load_snapshot: transaction onerror")}};e.onerror=()=>{console.log("fs_js_load_snapshot: open_request onerror")}},oc:function(a,b,c,d){const e=a?D(t,a):"";console.log("fs_js_save_snapshot: called with",
e,b);let g;try{g=window.indexedDB.open("chips",1)}catch(h){console.log("fs_js_save_snapshot: failed to open IndexedDB with "+h);return}g.onupgradeneeded=()=>{console.log("fs_js_save_snapshot: creating db");g.result.createObjectStore("store")};g.onsuccess=()=>{console.log("fs_js_save_snapshot: onsuccess");const h=g.result.transaction(["store"],"readwrite");var l=h.objectStore("store");const m=e+"_"+b;l=l.put(t.subarray(c,c+d),m);l.onsuccess=()=>{console.log("fs_js_save_snapshot:",m,"successfully stored")};
l.onerror=()=>{console.log("fs_js_save_snapshot: FAILED to store",m)};h.onerror=()=>{console.log("fs_js_save_snapshot: transaction onerror")}};g.onerror=()=>{console.log("fs_js_save_snapshot: open_request onerror")}},p:a=>N.activeTexture(a),y:(a,b)=>{N.attachShader(P[a],R[b])},b:(a,b)=>{34962==a?N.ud=b:34963==a&&(N.yd=b);35051==a?N.Yd=b:35052==a&&(N.vd=b);N.bindBuffer(a,O[b])},a:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},i:(a,b)=>{N.bindFramebuffer(a,Eb[b])},Ra:(a,b)=>{N.bindRenderbuffer(a,Fb[b])},o:(a,
b)=>{N.bindSampler(a,S[b])},d:(a,b)=>{N.bindTexture(a,Q[b])},P:a=>{N.bindVertexArray(Gb[a]);a=N.getParameter(34965);N.yd=a?a.name|0:0},ua:(a,b,c,d)=>N.blendColor(a,b,c,d),wa:(a,b)=>N.blendEquationSeparate(a,b),xa:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Ub:(a,b,c,d,e,g,h,l,m,p)=>N.blitFramebuffer(a,b,c,d,e,g,h,l,m,p),Ta:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,c?t.subarray(c,c+b):b,d)},M:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,
b,t.subarray(d,d+c))},E:a=>N.checkFramebufferStatus(a),mc:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),Ba:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},lc:(a,b,c)=>{N.clearBufferiv(a,b,u,c>>2)},m:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Bb:a=>{N.compileShader(R[a])},La:(a,b,c,d,e,g,h,l,m)=>{2<=V.version?N.vd||!l?N.compressedTexSubImage2D(a,b,c,d,e,g,h,l,m):N.compressedTexSubImage2D(a,b,c,d,e,g,h,t,m,l):N.compressedTexSubImage2D(a,b,c,d,e,g,h,t.subarray(m,m+l))},Ka:(a,b,c,d,e,g,h,l,m,p,w)=>{N.vd?N.compressedTexSubImage3D(a,
b,c,d,e,g,h,l,m,p,w):N.compressedTexSubImage3D(a,b,c,d,e,g,h,l,m,t,w,p)},Ia:()=>{var a=Mb(P),b=N.createProgram();b.name=a;b.Ed=b.Cd=b.Dd=0;b.Ud=1;P[a]=b;return a},Db:a=>{var b=Mb(R);R[b]=N.createShader(a);return b},ta:a=>N.cullFace(a),Eb:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.ud&&(N.ud=0),d==N.yd&&(N.yd=0),d==N.Yd&&(N.Yd=0),d==N.vd&&(N.vd=0))}},f:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=Eb[d];e&&(N.deleteFramebuffer(e),e.name=0,
Eb[d]=null)}},j:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},N:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Fb[d];e&&(N.deleteRenderbuffer(e),e.name=0,Fb[d]=null)}},t:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},n:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},O:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},Va:(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2];N.deleteVertexArray(Gb[d]);Gb[d]=null}},u:a=>N.depthFunc(a),v:a=>{N.depthMask(!!a)},e:a=>N.disable(a),ra:a=>{V.sd[a].enabled=!1;N.disableVertexAttribArray(a)},Wb:(a,b,c)=>{Pb(b+c);N.drawArrays(a,b,c);Ob&&N.bindBuffer(34962,O[N.ud])},Xb:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},D:(a,b)=>{for(var c=$b[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];N.drawBuffers(c)},Zb:(a,b,c,d)=>{var e=0;if(!N.yd){var g=1*Ib[c-5120]*b;var h=Nb(g);N.bindBuffer(34963,h);N.bufferSubData(34963,0,t.subarray(d,d+g));if(0<
b)for(h=0;h<V.Od;++h)if(g=V.sd[h],g.td&&g.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:T||=1282;return}e=(new e(t.buffer,d,b)).reduce((l,m)=>Math.max(l,m))+1;break}d=0}Pb(e);N.drawElements(a,b,c,d);Ob&&N.bindBuffer(34962,O[N.ud]);N.yd||N.bindBuffer(34963,null)},Yb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},h:a=>N.enable(a),hc:a=>{V.sd[a].enabled=!0;N.enableVertexAttribArray(a)},F:(a,b,c,d)=>{N.framebufferRenderbuffer(a,
b,c,Fb[d])},l:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},x:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},sa:a=>N.frontFace(a),Ua:(a,b)=>{U(a,b,"createBuffer",O)},G:(a,b)=>{U(a,b,"createFramebuffer",Eb)},Sa:(a,b)=>{U(a,b,"createRenderbuffer",Fb)},Ja:(a,b)=>{U(a,b,"createSampler",S)},Pa:(a,b)=>{U(a,b,"createTexture",Q)},Ya:(a,b)=>{U(a,b,"createVertexArray",Gb)},Ea:(a,b)=>N.getAttribLocation(P[a],b?D(t,b):""),c:(a,b)=>bc(a,b),Ga:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a=
"(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(u[c>>2]=b)},I:(a,b,c)=>{if(c)if(a>=Db)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Ed){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ed=Math.max(a.Ed,N.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.Ed}else if(35722==b){if(!a.Cd)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Cd=Math.max(a.Cd,N.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Cd}else if(35381==
b){if(!a.Dd)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Dd=Math.max(a.Dd,N.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Dd}else u[c>>2]=N.getProgramParameter(a,b);else T||=1281},Ab:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(u[c>>2]=b)},la:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=N.getShaderParameter(R[a],
b):T||=1281},Za:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Jb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=ac().map(dc),c=Jb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},H:(a,b)=>{b=b?D(t,b):"";if(a=P[a]){var c=a,d=c.Bd,e=c.pe,g;if(!d){c.Bd=d={};c.oe={};var h=N.getProgramParameter(c,35718);for(g=0;g<h;++g){var l=N.getActiveUniform(c,g);var m=l.name;l=l.size;var p=ec(m);p=0<p?m.slice(0,p):m;var w=c.Ud;c.Ud+=l;e[p]=[l,w];for(m=0;m<l;++m)d[w]=
m,c.oe[w++]=p}}c=a.Bd;d=0;e=b;g=ec(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.pe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},Tb:(a,b,c)=>{for(var d=$b[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];N.invalidateFramebuffer(a,d)},J:a=>{a=P[a];N.linkProgram(a);a.Bd=0;a.pe={}},Xa:(a,b)=>{3317==a?Kb=b:3314==a&&(Lb=b);N.pixelStorei(a,b)},Aa:(a,b)=>N.polygonOffset(a,b),Vb:a=>N.readBuffer(a),Qa:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),K:(a,
b,c)=>{N.samplerParameterf(S[a],b,c)},g:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},w:(a,b,c,d)=>N.scissor(a,b,c,d),Cb:(a,b,c,d)=>{for(var e="",g=0;g<b;++g){var h=(h=v[c+4*g>>2])?D(t,h,d?v[d+4*g>>2]:void 0):"";e+=h}N.shaderSource(R[a],e)},Gb:(a,b,c)=>N.stencilFunc(a,b,c),za:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),q:a=>N.stencilMask(a),Fb:(a,b,c)=>N.stencilOp(a,b,c),ya:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Oa:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ma:(a,b,c,d,e,g)=>N.texStorage3D(a,b,c,d,e,g),s:(a,
b,c,d,e,g,h,l,m)=>{if(2<=V.version){if(N.vd){N.texSubImage2D(a,b,c,d,e,g,h,l,m);return}if(m){var p=fc(l);N.texSubImage2D(a,b,c,d,e,g,h,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(m){p=fc(l);var w=g*((Lb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*p.BYTES_PER_ELEMENT+Kb-1&-Kb);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),m+w>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;N.texSubImage2D(a,b,c,d,e,g,h,l,m)},L:(a,b,c,d,e,g,h,l,m,p,w)=>{if(N.vd)N.texSubImage3D(a,
b,c,d,e,g,h,l,m,p,w);else if(w){var H=fc(p);N.texSubImage3D(a,b,c,d,e,g,h,l,m,p,H,w>>>31-Math.clz32(H.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,g,h,l,m,p,null)},gc:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Fa:(a,b)=>{N.uniform1i(W(a),b)},cc:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=gc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=
u.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},fc:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},bc:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=gc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},ec:(a,b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),
x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},ac:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b){b*=3;for(var d=gc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},dc:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],
e=x;c>>=2;b*=4;for(var g=0;g<b;g+=4){var h=c+g;d[g]=e[h];d[g+1]=e[h+1];d[g+2]=e[h+2];d[g+3]=e[h+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},$b:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=gc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},_b:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=
X[16*b],g=x;d>>=2;b*=16;for(var h=0;h<b;h+=16){var l=d+h;e[h]=g[l];e[h+1]=g[l+1];e[h+2]=g[l+2];e[h+3]=g[l+3];e[h+4]=g[l+4];e[h+5]=g[l+5];e[h+6]=g[l+6];e[h+7]=g[l+7];e[h+8]=g[l+8];e[h+9]=g[l+9];e[h+10]=g[l+10];e[h+11]=g[l+11];e[h+12]=g[l+12];e[h+13]=g[l+13];e[h+14]=g[l+14];e[h+15]=g[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=P[a];N.useProgram(a);N.re=a},ic:(a,b)=>{N.vertexAttribDivisor(a,b)},jc:(a,b,c,d,e)=>{var g=V.sd[a];N.ud?(g.td=!1,N.vertexAttribIPointer(a,
b,c,d,e)):(g.size=b,g.type=c,g.Pd=!1,g.Hd=d,g.Gd=e,g.td=!0,g.Vd=function(h,l,m,p,w,H){this.vertexAttribIPointer(h,l,m,w,H)})},kc:(a,b,c,d,e,g)=>{var h=V.sd[a];N.ud?(h.td=!1,N.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.Pd=d,h.Hd=e,h.Gd=g,h.td=!0,h.Vd=function(l,m,p,w,H,E){this.vertexAttribPointer(l,m,p,w,H,E)})},r:(a,b,c,d)=>N.viewport(a,b,c,d),lb:Ma,jb:function(){f.he=a=>{0!=qc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.he)},ib:function(){f.ne=
a=>{const b=a.clipboardData.getData("text");B(()=>{const c=C(b);rc(c)})};window.addEventListener("paste",f.ne)},hb:function(){f.Se=[];f.ie=b=>{b.stopPropagation();b.preventDefault()};f.je=b=>{b.stopPropagation();b.preventDefault()};f.ke=b=>{b.stopPropagation();b.preventDefault()};f.le=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.me=c;sc(c.length);for(let e=0;e<c.length;e++)B(()=>{const g=C(c[e].name);tc(e,g)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=
4);b.metaKey&&(d|=8);uc(b.clientX,b.clientY,d)};const a=f.od;a.addEventListener("dragenter",f.ie,!1);a.addEventListener("dragleave",f.je,!1);a.addEventListener("dragover",f.ke,!1);a.addEventListener("drop",f.le,!1)},bb:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},$a:function(a){const b=f.me;return 0>a||a>=b.length?0:b[a].size},_a:function(a,b,c,d,e){const g=new FileReader;g.onload=h=>{h=h.target.result;h.byteLength>d?vc(a,0,1,b,0,c,d,e):(t.set(new Uint8Array(h),
c),vc(a,1,0,b,h.byteLength,c,d,e))};g.onerror=()=>{vc(a,0,2,b,0,c,d,e)};g.readAsArrayBuffer(f.me[a])},Da:function(a,b){0!==b&&(document.title=b?D(t,b):"");a=a?D(t,a):"";void 0!==f.canvas&&("object"===typeof f.canvas?nb[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));f.od=K(a);f.od||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.od.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Kb:function(){window.removeEventListener("beforeunload",
f.he)},Jb:function(){window.removeEventListener("paste",f.ne)},Ib:function(){const a=f.od;a.removeEventListener("dragenter",f.ie);a.removeEventListener("dragleave",f.je);a.removeEventListener("dragover",f.ke);a.removeEventListener("drop",f.le)},A:function(){f.od&&f.od.requestPointerLock&&f.od.requestPointerLock()},db:function(a,b){if(f.od){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a=
"ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.od.style.cursor=a}},ab:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),g=e.createImageData(a,b);g.data.set(t.subarray(c,c+a*b*4));e.putImageData(g,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
cb:function(a){a=a?D(t,a):"";const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},Nb:function(){const a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=
a.next()){const c=b.value[0],d=b.value[1];B(()=>{const e=C(c),g=C(d);wc(e,g)})}},Qb:function(){return f.pd?f.pd.bufferSize:0},Sb:function(a,b,c){f.hd=null;f.pd=null;"undefined"!==typeof AudioContext?f.hd=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(f.hd=null,console.log("sokol_audio.h: no WebAudio support"));return f.hd?(console.log("sokol_audio.h: sample rate ",f.hd.sampleRate),f.pd=f.hd.createScriptProcessor(c,0,b),f.pd.onaudioprocess=d=>{const e=d.outputBuffer.length,g=xc(e);if(g){const h=
d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(g>>2)+(h*p+l)]}}},f.pd.connect(f.hd.destination),a=()=>{f.hd&&"suspended"===f.hd.state&&f.hd.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},Rb:function(){return f.hd?f.hd.sampleRate:0},oa:function(){const a=f.hd;null!==a&&(f.pd&&f.pd.disconnect(),a.close(),f.hd=null,
f.pd=null)},Ob:function(){if(f.hd)return"suspended"===f.hd.state?1:0},B:function(a,b,c,d,e,g){const h=b?D(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(h,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=g?(t.set(m,e),yc(a,d,m.length)):zc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,m);Ac(a)}):Bc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${h} failed with: `,l);Ac(a)})},na:function(a,b){const c=
b?D(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),Ac(a)):Cc(a,Number(d))):Bc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);Ac(a)})},ka:function(){return navigator.userAgent.includes("Macintosh")?1:0},ma:function(a,b){b=b?D(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}},
Wa:function(){console.log("webapi_js_event_continued()");f.webapi_onContinued?f.webapi_onContinued():console.log("no Module.webapi_onContinued function")},Na:function(){console.log("webapi_js_event_reboot()");f.webapi_onReboot?f.webapi_onReboot():console.log("no Module.webapi_onReboot function")},Ha:function(){console.log("webapi_js_event_reset()");f.webapi_onReset?f.webapi_onReset():console.log("no Module.webapi_onReset function")},z:function(a,b){console.log("webapi_js_event_stopped()");f.webapi_onStopped?
f.webapi_onStopped(a,b):console.log("no Module.webapi_onStopped function")}},Z;(async function(){function a(c){Z=c.exports;na=Z.pc;ta();qb=Z.uc;va.unshift(Z.qc);z--;f.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;f.monitorRunDependencies?.(z);var b={a:Dc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(c){return n(`Module.instantiateWasm callback failed with error: ${c}`),!1}Aa??=sa("emu.wasm")?"emu.wasm":f.locateFile?f.locateFile("emu.wasm",k):k+"emu.wasm";return a((await Da(b)).instance)})();
var oc=f._fs_emsc_alloc=a=>(oc=f._fs_emsc_alloc=Z.rc)(a),M=a=>(M=Z.sc)(a),pc=f._fs_emsc_load_snapshot_callback=(a,b,c)=>(pc=f._fs_emsc_load_snapshot_callback=Z.tc)(a,b,c);f._webapi_dbg_connect=()=>(f._webapi_dbg_connect=Z.vc)();f._webapi_dbg_disconnect=()=>(f._webapi_dbg_disconnect=Z.wc)();f._webapi_alloc=a=>(f._webapi_alloc=Z.xc)(a);f._webapi_free=a=>(f._webapi_free=Z.yc)(a);f._webapi_boot=()=>(f._webapi_boot=Z.zc)();f._webapi_reset=()=>(f._webapi_reset=Z.Ac)();
f._webapi_ready=()=>(f._webapi_ready=Z.Bc)();f._webapi_load=(a,b)=>(f._webapi_load=Z.Cc)(a,b);f._webapi_load_file_internal=a=>(f._webapi_load_file_internal=Z.Dc)(a);f._webapi_unload_file=()=>(f._webapi_unload_file=Z.Ec)();f._webapi_load_snapshot=a=>(f._webapi_load_snapshot=Z.Fc)(a);f._webapi_save_snapshot=a=>(f._webapi_save_snapshot=Z.Gc)(a);f._webapi_dbg_add_breakpoint=a=>(f._webapi_dbg_add_breakpoint=Z.Hc)(a);f._webapi_dbg_remove_breakpoint=a=>(f._webapi_dbg_remove_breakpoint=Z.Ic)(a);
f._webapi_dbg_break=()=>(f._webapi_dbg_break=Z.Jc)();f._webapi_dbg_continue=()=>(f._webapi_dbg_continue=Z.Kc)();f._webapi_dbg_step_next=()=>(f._webapi_dbg_step_next=Z.Lc)();f._webapi_dbg_step_into=()=>(f._webapi_dbg_step_into=Z.Mc)();f._webapi_dbg_cpu_state=()=>(f._webapi_dbg_cpu_state=Z.Nc)();f._webapi_dbg_request_disassembly=(a,b,c)=>(f._webapi_dbg_request_disassembly=Z.Oc)(a,b,c);f._webapi_dbg_read_memory=(a,b)=>(f._webapi_dbg_read_memory=Z.Pc)(a,b);
f._webapi_input_internal=a=>(f._webapi_input_internal=Z.Qc)(a);
var rc=f.__sapp_emsc_onpaste=a=>(rc=f.__sapp_emsc_onpaste=Z.Rc)(a),qc=f.__sapp_html5_get_ask_leave_site=()=>(qc=f.__sapp_html5_get_ask_leave_site=Z.Sc)(),sc=f.__sapp_emsc_begin_drop=a=>(sc=f.__sapp_emsc_begin_drop=Z.Tc)(a),tc=f.__sapp_emsc_drop=(a,b)=>(tc=f.__sapp_emsc_drop=Z.Uc)(a,b),uc=f.__sapp_emsc_end_drop=(a,b,c)=>(uc=f.__sapp_emsc_end_drop=Z.Vc)(a,b,c),vc=f.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,g,h,l)=>(vc=f.__sapp_emsc_invoke_fetch_cb=Z.Wc)(a,b,c,d,e,g,h,l),Ec=f._main=(a,b)=>(Ec=f._main=Z.Xc)(a,
b),xc=f.__saudio_emsc_pull=a=>(xc=f.__saudio_emsc_pull=Z.Yc)(a),wc=f.__sargs_add_kvp=(a,b)=>(wc=f.__sargs_add_kvp=Z.Zc)(a,b),Cc=f.__sfetch_emsc_head_response=(a,b)=>(Cc=f.__sfetch_emsc_head_response=Z._c)(a,b),yc=f.__sfetch_emsc_get_response=(a,b,c)=>(yc=f.__sfetch_emsc_get_response=Z.$c)(a,b,c),Bc=f.__sfetch_emsc_failed_http_status=(a,b)=>(Bc=f.__sfetch_emsc_failed_http_status=Z.ad)(a,b),zc=f.__sfetch_emsc_failed_buffer_too_small=a=>(zc=f.__sfetch_emsc_failed_buffer_too_small=Z.bd)(a),Ac=f.__sfetch_emsc_failed_other=
a=>(Ac=f.__sfetch_emsc_failed_other=Z.cd)(a),nc=(a,b)=>(nc=Z.dd)(a,b),jc=a=>(jc=Z.ed)(a),hc=a=>(hc=Z.fd)(a),ic=()=>(ic=Z.gd)();function Fc(a=[]){var b=Ec;a.unshift(fa);var c=a.length,d=hc(4*(c+1)),e=d;a.forEach(h=>{v[e>>2]=C(h);e+=4});v[e>>2]=0;try{var g=b(c,d);Na(g)}catch(h){La(h)}}
function Gc(a=ea){function b(){f.calledRun=!0;if(!q){Ga(va);Ga(wa);f.onRuntimeInitialized?.();f.noInitialRun||Fc(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ga(xa)}}if(0<z)A=Gc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ga(ua);0<z?A=Gc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Gc();
